### ISSUE TITLE
v0.9.0 build is broken

### ISSUE THREAD

**Issue by bergwolf** [cloud-hypervisor/cloud-hypervisor#1723] opened 2020-09-18 14:26 UTC
It depends on `https://github.com/cloud-hypervisor/kvm-ioctls/commit/37953e96` but the exact commit is removed from `cloud-hypervisor/kvm-ioctls` `ch` branch, causing `v0.9.0` build to fail.

```
    Updating git repository `https://github.com/cloud-hypervisor/vm-memory`
    Updating git submodule `https://github.com/rust-vmm/rust-vmm-ci.git`
    Updating crates.io index
    Updating git repository `https://github.com/rust-vmm/linux-loader`
    Updating git submodule `https://github.com/rust-vmm/rust-vmm-ci.git`
    Updating git repository `https://github.com/cloud-hypervisor/kvm-bindings`
    Updating git submodule `https://github.com/rust-vmm/rust-vmm-ci.git`
    Updating git repository `https://github.com/cloud-hypervisor/kvm-ioctls`
error: failed to get `kvm-ioctls` as a dependency of package `hypervisor v0.1.0 (/home/runner/work/kata-containers/kata-containers/tools/packaging/release/cloud-hypervisor/hypervisor)`

Caused by:
  failed to load source for dependency `kvm-ioctls`

Caused by:
  Unable to update https://github.com/cloud-hypervisor/kvm-ioctls?branch=ch#37953e96

Caused by:
  object not found - no match for id (37953e968b9064f42d6b71b7afc13872ac4171ce); class=Odb (9); code=NotFound (-3)
##[error]Process completed with exit code 101.
```

github can still find the exact commit (https://github.com/cloud-hypervisor/kvm-ioctls/commit/37953e96) but reports that
```
This commit does not belong to any branch on this repository. 
```

**Comment by bergwolf** [comment] 2020-09-18 14:30
And this is blocking Kata Containers 2.0.0-rc0 release. See https://github.com/kata-containers/kata-containers/actions/runs/260953909

We can possibly update Kata to use the just released `v0.10.0` instead (which did build successfully https://github.com/bergwolf/kata-containers/actions/runs/261260655) but want to confirm with the clh maintainers if `v0.10.0` is compatible with `v0.9.0`.

@sameo @sboeuf Please help to take a look.

**Comment by bergwolf** [comment] 2020-09-18 15:04
NVM, I've changed Kata to download the official release binary instead. It is still worth fixing but it doesn't block Kata release any more.

Ref: https://github.com/kata-containers/kata-containers/pull/761

**Comment by rbradford** [comment] 2020-09-18 15:05
I think you should use 0.10.0

**Comment by rbradford** [comment] 2020-09-18 15:10
At this point in time, due to the fast moving nature of the project, I don't think we can guarantee that old releases will continue to build. In this case the issue is a flaw with cargo that requires commits that are pointed to by hash also be on the corresponding branch.

To avoid this happening in the future we will stop rebasing our fork branches and continue to try and eliminate our forks.

**Comment by likebreath** [comment] 2020-09-19 16:49
The packaging issue of cloud-hypervisor in kata 2.0 should be fixed now. Together with @bergwolf patch to pull directly from released binaries, this patch (https://github.com/kata-containers/kata-containers/pull/762/commits/bf59689f0c3e65ff1919b82059130d9beac305c2) added a fall back path that builds cloud-hypervisor from source w/ its own container image. This gives the flexibility to use not only released version of clh in Kata if needed. Also, I verified this fall back works for building clh v0.9.0 from source. 

I am closing the issue now. Any other questions, please let us know. Thank you. @bergwolf

**Closed by likebreath** 2020-09-19 16:49 UTC
