### ISSUE TITLE
Unable to use virtio console ("Error -28 initializing vqs")

### ISSUE THREAD

**Issue by larsks** [cloud-hypervisor/cloud-hypervisor#6554] opened 2024-06-22 01:23 UTC
**Describe the bug**

I would like to use a virtio console with my virtual machine. I am booting a kernel with virtio console support. Using qemu, I can run:

```
qemu-system-x86_64 -m 1g -accel kvm -M microvm -nographic \
  -kernel arch/x86/boot/bzImage \
  -initrd initrd \
  -append console=hvc0 \
  -device virtio-serial-device,id=virtio-serial0 \
  -chardev stdio,mux=on,id=console \
  -device virtconsole,chardev=console,bus=virtio-serial0.0,id=port1,nr=1 \
  -serial none \
  -mon chardev=console,mode=readline
```

That works, and I end up with a `/dev/hvc0` device in the virtual machine and the expected console in my local terminal.

I am trying to achieve the same thing using `cloud-hypervisor` like this:

```
cloud-hypervisor --memory size=1G \
  --kernel vmlinux \
  --initramfs initrd \
  --cmdline console=hvc0 \
  --serial off \
  --console tty
```

That gets me nothing.

If I do this instead:

```
cloud-hypervisor --memory size=1G \
  --kernel vmlinux \
  --initramfs initrd \
  --cmdline console=hvc0 \
  --serial tty \
  --console file=console.log
```

Then I can log in as expected, but there are no virtio console devices in `/dev`:

```
(none):/# ls /dev/hvc*
ls: /dev/hvc*: No such file or directory
```

On the serial console, I see the following errors:

```
virtio_console virtio0: Error -28 initializing vqs
virtio_console virtio0: probe with driver virtio_console failed with error -28
virtio_rng virtio2: probe with driver virtio_rng failed with error -28
virtio_net virtio1: probe with driver virtio_net failed with error -28
```

**To Reproduce**

See above.

**Version**

Output of `cloud-hypervisor --version`:

```
cloud-hypervisor v38.0.0
```

Did you build from source, if so build command line (e.g. features):

This was installed from the OBS repo for Fedora 39.

**VM configuration**

See above.

Guest OS version details: Linux kernel v6.10-rc4-179-g4545981f33be

Host OS version details: Fedora 40 (kernel 6.9.4-200.fc40.x86_64)

**Logs**

Output of `cloud-hypervisor -v` from either standard error or via `--log-file`:

```
cloud-hypervisor: 1.709060ms: <vmm> INFO:vmm/src/api/mod.rs:832 -- API request event: VmCreate Mutex { data: VmConfig { cpus: CpusConfig { boot_vcpus: 4, max_vcpus: 4, topology: None, kvm_hyperv: false, max_phys_bits: 46, affinity: None, features: CpuFeatures { amx: false } }, memory: MemoryConfig { size: 1073741824, mergeable: false, hotplug_method: Acpi, hotplug_size: None, hotplugged_size: None, shared: false, hugepages: false, hugepage_size: None, prefault: false, zones: None, thp: true }, payload: Some(PayloadConfig { firmware: None, kernel: Some("vmlinux"), cmdline: Some("console=hvc0"), initramfs: Some("initrd") }), rate_limit_groups: None, disks: None, net: Some([NetConfig { tap: None, ip: 192.168.249.1, mask: 255.255.255.0, mac: MacAddr { bytes: [46, 143, 68, 235, 155, 255] }, host_mac: None, mtu: None, iommu: false, num_queues: 2, queue_size: 256, vhost_user: false, vhost_socket: None, vhost_mode: Client, id: None, fds: None, rate_limiter_config: None, pci_segment: 0, offload_tso: true, offload_ufo: true, offload_csum: true }]), rng: RngConfig { src: "/dev/urandom", iommu: false }, balloon: None, fs: None, pmem: None, serial: ConsoleConfig { file: None, mode: Tty, iommu: false, socket: None }, console: ConsoleConfig { file: Some("console.log"), mode: File, iommu: false, socket: None }, debug_console: DebugConsoleConfig { file: None, mode: Off, iobase: Some(233) }, devices: None, user_devices: None, vdpa: None, vsock: None, pvpanic: false, iommu: false, sgx_epc: None, numa: None, watchdog: false, platform: None, tpm: None, preserved_fds: None }, poisoned: false, .. }
cloud-hypervisor: 2.767262ms: <vmm> INFO:vmm/src/api/mod.rs:723 -- API request event: VmBoot
cloud-hypervisor: 17.777332ms: <vmm> INFO:vmm/src/memory_manager.rs:587 -- create ram region for zone mem0, region_start: 0x0, region_size: 0x40000000
cloud-hypervisor: 17.823640ms: <vmm> INFO:vmm/src/memory_manager.rs:1511 -- Anonymous mapping at 0x7f4ba8000000 (size = 0x40000000)
cloud-hypervisor: 17.876046ms: <vmm> INFO:vmm/src/vm.rs:502 -- Booting VM from config: Mutex { data: VmConfig { cpus: CpusConfig { boot_vcpus: 4, max_vcpus: 4, topology: None, kvm_hyperv: false, max_phys_bits: 46, affinity: None, features: CpuFeatures { amx: false } }, memory: MemoryConfig { size: 1073741824, mergeable: false, hotplug_method: Acpi, hotplug_size: None, hotplugged_size: None, shared: false, hugepages: false, hugepage_size: None, prefault: false, zones: None, thp: true }, payload: Some(PayloadConfig { firmware: None, kernel: Some("vmlinux"), cmdline: Some("console=hvc0"), initramfs: Some("initrd") }), rate_limit_groups: None, disks: None, net: Some([NetConfig { tap: None, ip: 192.168.249.1, mask: 255.255.255.0, mac: MacAddr { bytes: [46, 143, 68, 235, 155, 255] }, host_mac: None, mtu: None, iommu: false, num_queues: 2, queue_size: 256, vhost_user: false, vhost_socket: None, vhost_mode: Client, id: None, fds: None, rate_limiter_config: None, pci_segment: 0, offload_tso: true, offload_ufo: true, offload_csum: true }]), rng: RngConfig { src: "/dev/urandom", iommu: false }, balloon: None, fs: None, pmem: None, serial: ConsoleConfig { file: None, mode: Tty, iommu: false, socket: None }, console: ConsoleConfig { file: Some("console.log"), mode: File, iommu: false, socket: None }, debug_console: DebugConsoleConfig { file: None, mode: Off, iobase: Some(233) }, devices: None, user_devices: None, vdpa: None, vsock: None, pvpanic: false, iommu: false, sgx_epc: None, numa: None, watchdog: false, platform: None, tpm: None, preserved_fds: None }, poisoned: false, .. }
cloud-hypervisor: 18.368941ms: <vmm> INFO:arch/src/x86_64/mod.rs:592 -- Generating guest CPUID for with physical address size: 39
cloud-hypervisor: 17.950303ms: <payload_loader> INFO:vmm/src/vm.rs:1032 -- Loading kernel
cloud-hypervisor: 18.409879ms: <vmm> INFO:vmm/src/cpu.rs:873 -- Request to create new vCPUs: desired = 4, max = 4, allocated = 0, present = 0
cloud-hypervisor: 18.451223ms: <vmm> INFO:vmm/src/cpu.rs:777 -- Creating vCPU: cpu_id = 0
cloud-hypervisor: 18.711257ms: <vmm> INFO:vmm/src/cpu.rs:777 -- Creating vCPU: cpu_id = 1
cloud-hypervisor: 18.770246ms: <vmm> INFO:vmm/src/cpu.rs:777 -- Creating vCPU: cpu_id = 2
cloud-hypervisor: 18.821325ms: <vmm> INFO:vmm/src/cpu.rs:777 -- Creating vCPU: cpu_id = 3
cloud-hypervisor: 18.882298ms: <vmm> INFO:vmm/src/pci_segment.rs:104 -- Adding PCI segment: id=0, PCI MMIO config address: 0xe8000000, mem32 area [0xc0000000-0xe7ffffff, mem64 area [0x100000000-0x7effffffff
cloud-hypervisor: 19.037745ms: <vmm> INFO:vmm/src/device_manager.rs:2600 -- Creating virtio-net device: NetConfig { tap: None, ip: 192.168.249.1, mask: 255.255.255.0, mac: MacAddr { bytes: [46, 143, 68, 235, 155, 255] }, host_mac: None, mtu: None, iommu: false, num_queues: 2, queue_size: 256, vhost_user: false, vhost_socket: None, vhost_mode: Client, id: Some("_net0"), fds: None, rate_limiter_config: None, pci_segment: 0, offload_tso: true, offload_ufo: true, offload_csum: true }
cloud-hypervisor: 20.314641ms: <vmm> INFO:vmm/src/device_manager.rs:2773 -- Creating virtio-rng device: RngConfig { src: "/dev/urandom", iommu: false }
cloud-hypervisor: 22.564432ms: <vmm> INFO:vmm/src/vm.rs:2011 -- Booting VM
cloud-hypervisor: 22.979175ms: <vmm> INFO:vmm/src/acpi.rs:830 -- Generated ACPI tables: took 368µs size = 5519
cloud-hypervisor: 23.020266ms: <vmm> INFO:vmm/src/vm.rs:1995 -- Created ACPI tables: rsdp_addr = 0xa0000
cloud-hypervisor: 24.957440ms: <payload_loader> INFO:vmm/src/vm.rs:1053 -- Kernel loaded: entry_addr = 0x1000000
cloud-hypervisor: 25.045212ms: <vmm> INFO:vmm/src/cpu.rs:381 -- Configuring vCPU: cpu_id = 0
cloud-hypervisor: 25.114718ms: <vmm> INFO:vmm/src/cpu.rs:381 -- Configuring vCPU: cpu_id = 1
cloud-hypervisor: 25.159689ms: <vmm> INFO:vmm/src/cpu.rs:381 -- Configuring vCPU: cpu_id = 2
cloud-hypervisor: 25.202275ms: <vmm> INFO:vmm/src/cpu.rs:381 -- Configuring vCPU: cpu_id = 3
cloud-hypervisor: 25.244194ms: <vmm> INFO:vmm/src/vm.rs:1149 -- Configuring system
cloud-hypervisor: 29.278336ms: <vmm> INFO:vmm/src/vm.rs:935 -- Initramfs loaded: address = 0x3f029000
cloud-hypervisor: 29.342759ms: <vmm> INFO:arch/src/x86_64/mod.rs:994 -- first usable physical memory range, start: 0x00100000, end: 0x40000000
cloud-hypervisor: 29.385295ms: <vmm> INFO:arch/src/x86_64/mod.rs:1068 -- create_memmap_entry, start: 0x00100000, end: 0x40000000
cloud-hypervisor: 29.419674ms: <vmm> INFO:vmm/src/memory_manager.rs:1748 -- Creating userspace mapping: 0 -> 7f4ba8000000 40000000, slot 0
cloud-hypervisor: 29.479810ms: <vmm> INFO:vmm/src/memory_manager.rs:1796 -- Created userspace mapping: 0 -> 7f4ba8000000 40000000
cloud-hypervisor: 29.507540ms: <vmm> INFO:vmm/src/cpu.rs:1196 -- Starting vCPUs: desired = 4, allocated = 4, present = 0, paused = false
cloud-hypervisor: 29.550902ms: <vmm> INFO:vmm/src/cpu.rs:969 -- Starting vCPU: cpu_id = 0
cloud-hypervisor: 29.609112ms: <vmm> INFO:vmm/src/cpu.rs:969 -- Starting vCPU: cpu_id = 1
cloud-hypervisor: 29.675650ms: <vmm> INFO:vmm/src/cpu.rs:969 -- Starting vCPU: cpu_id = 2
cloud-hypervisor: 29.737387ms: <vmm> INFO:vmm/src/cpu.rs:969 -- Starting vCPU: cpu_id = 3
cloud-hypervisor: 31.881187ms: <vcpu0> INFO:vmm/src/vm.rs:424 -- Guest PIO write to unregistered address 0x43
cloud-hypervisor: 31.912568ms: <vcpu0> INFO:vmm/src/vm.rs:424 -- Guest PIO write to unregistered address 0x42
cloud-hypervisor: 31.937005ms: <vcpu0> INFO:vmm/src/vm.rs:424 -- Guest PIO write to unregistered address 0x42
cloud-hypervisor: 31.958685ms: <vcpu0> INFO:vmm/src/vm.rs:415 -- Guest PIO read to unregistered address 0x42
cloud-hypervisor: 31.980384ms: <vcpu0> INFO:vmm/src/vm.rs:415 -- Guest PIO read to unregistered address 0x42
cloud-hypervisor: 32.001891ms: <vcpu0> INFO:vmm/src/vm.rs:415 -- Guest PIO read to unregistered address 0x42
cloud-hypervisor: 32.023175ms: <vcpu0> INFO:vmm/src/vm.rs:415 -- Guest PIO read to unregistered address 0x42
cloud-hypervisor: 388.034903ms: <vcpu0> INFO:vmm/src/vm.rs:415 -- Guest PIO read to unregistered address 0x87
cloud-hypervisor: 400.048822ms: <vcpu0> INFO:vmm/src/vm.rs:415 -- Guest PIO read to unregistered address 0x2f9
cloud-hypervisor: 400.079500ms: <vcpu0> INFO:vmm/src/vm.rs:424 -- Guest PIO write to unregistered address 0x2f9
cloud-hypervisor: 400.115693ms: <vcpu0> INFO:vmm/src/vm.rs:415 -- Guest PIO read to unregistered address 0x2f9
cloud-hypervisor: 400.136897ms: <vcpu0> INFO:vmm/src/vm.rs:424 -- Guest PIO write to unregistered address 0x2f9
cloud-hypervisor: 400.160029ms: <vcpu0> INFO:vmm/src/vm.rs:415 -- Guest PIO read to unregistered address 0x2f9
cloud-hypervisor: 400.180832ms: <vcpu0> INFO:vmm/src/vm.rs:424 -- Guest PIO write to unregistered address 0x2f9
cloud-hypervisor: 400.218402ms: <vcpu0> INFO:vmm/src/vm.rs:415 -- Guest PIO read to unregistered address 0x3e9
cloud-hypervisor: 400.242980ms: <vcpu0> INFO:vmm/src/vm.rs:424 -- Guest PIO write to unregistered address 0x3e9
cloud-hypervisor: 400.270476ms: <vcpu0> INFO:vmm/src/vm.rs:415 -- Guest PIO read to unregistered address 0x3e9
cloud-hypervisor: 400.291212ms: <vcpu0> INFO:vmm/src/vm.rs:424 -- Guest PIO write to unregistered address 0x3e9
cloud-hypervisor: 400.311580ms: <vcpu0> INFO:vmm/src/vm.rs:415 -- Guest PIO read to unregistered address 0x3e9
cloud-hypervisor: 400.356523ms: <vcpu0> INFO:vmm/src/vm.rs:424 -- Guest PIO write to unregistered address 0x3e9
cloud-hypervisor: 400.410304ms: <vcpu0> INFO:vmm/src/vm.rs:415 -- Guest PIO read to unregistered address 0x2e9
cloud-hypervisor: 400.433992ms: <vcpu0> INFO:vmm/src/vm.rs:424 -- Guest PIO write to unregistered address 0x2e9
cloud-hypervisor: 400.454740ms: <vcpu0> INFO:vmm/src/vm.rs:415 -- Guest PIO read to unregistered address 0x2e9
cloud-hypervisor: 400.475309ms: <vcpu0> INFO:vmm/src/vm.rs:424 -- Guest PIO write to unregistered address 0x2e9
cloud-hypervisor: 400.495828ms: <vcpu0> INFO:vmm/src/vm.rs:415 -- Guest PIO read to unregistered address 0x2e9
cloud-hypervisor: 400.516326ms: <vcpu0> INFO:vmm/src/vm.rs:424 -- Guest PIO write to unregistered address 0x2e9
cloud-hypervisor: 26.270947s: <vcpu0> INFO:devices/src/acpi.rs:67 -- ACPI Shutdown signalled
cloud-hypervisor: 26.271022s: <vmm> INFO:vmm/src/lib.rs:1125 -- VM exit event
cloud-hypervisor: 26.271047s: <vmm> INFO:virtio-devices/src/device.rs:334 -- Resuming virtio-net
cloud-hypervisor: 26.271066s: <vmm> INFO:virtio-devices/src/device.rs:334 -- Resuming virtio-console
cloud-hypervisor: 26.271084s: <vmm> INFO:virtio-devices/src/device.rs:334 -- Resuming virtio-rng
cloud-hypervisor: 26.275678s: <serial-manager> INFO:vmm/src/serial_manager.rs:415 -- KILL_EVENT received, stopping epoll loop
```

Linux kernel output:

```
Linux version 6.10.0-rc4-ax25-00179-g4545981f33be (lars@madhatter) (gcc (GCC) 14.1.1 20240607 (Red Hat 14.1.1-5), GNU ld version 2.41-37.fc40) #180 SMP Fri Jun 21 15:14:51 EDT 2024
Command line: console=ttyS0,115200
BIOS-provided physical RAM map:
BIOS-e820: [mem 0x0000000000000000-0x000000000009ffff] usable
BIOS-e820: [mem 0x00000000000a0000-0x00000000000fffff] reserved
BIOS-e820: [mem 0x0000000000100000-0x000000003fffffff] usable
BIOS-e820: [mem 0x00000000e8000000-0x00000000f7ffffff] reserved
NX (Execute Disable) protection: active
APIC: Static calls initialized
SMBIOS 3.2.0 present.
DMI: Cloud Hypervisor cloud-hypervisor, BIOS 0 
DMI: Memory slots populated: 0/0
tsc: Fast TSC calibration failed
last_pfn = 0x40000 max_arch_pfn = 0x400000000
MTRR map: 0 entries (0 fixed + 0 variable; max 16), built from 8 variable MTRRs
x86/PAT: Configuration [0-7]: WB  WC  UC- UC  WB  WP  UC- WT  
found SMP MP-table at [mem 0x000f0090-0x000f009f]
Using GB pages for direct mapping
RAMDISK: [mem 0x3f029000-0x3fffffff]
ACPI: Early table checksum verification disabled
ACPI: RSDP 0x00000000000A0000 000024 (v02 CLOUDH)
ACPI: XSDT 0x00000000000A1553 00003C (v01 CLOUDH CHXSDT   00000001 RVAT 01000000)
ACPI: FACP 0x00000000000A1381 000114 (v06 CLOUDH CHFACP   00000001 RVAT 01000000)
ACPI: DSDT 0x00000000000A0024 00135D (v06 CLOUDH CHDSDT   00000001 RVAT 01000000)
ACPI: APIC 0x00000000000A1495 000082 (v05 CLOUDH CHMADT   00000001 RVAT 01000000)
ACPI: MCFG 0x00000000000A1517 00003C (v01 CLOUDH CHMCFG   00000001 RVAT 01000000)
ACPI: Reserving FACP table memory at [mem 0xa1381-0xa1494]
ACPI: Reserving DSDT table memory at [mem 0xa0024-0xa1380]
ACPI: Reserving APIC table memory at [mem 0xa1495-0xa1516]
ACPI: Reserving MCFG table memory at [mem 0xa1517-0xa1552]
Zone ranges:
  DMA      [mem 0x0000000000001000-0x0000000000ffffff]
  DMA32    [mem 0x0000000001000000-0x000000003fffffff]
  Normal   empty
Movable zone start for each node
Early memory node ranges
  node   0: [mem 0x0000000000001000-0x000000000009ffff]
  node   0: [mem 0x0000000000100000-0x000000003fffffff]
Initmem setup node 0 [mem 0x0000000000001000-0x000000003fffffff]
On node 0, zone DMA: 1 pages in unavailable ranges
On node 0, zone DMA: 96 pages in unavailable ranges
ACPI: PM-Timer IO Port: 0x608
ACPI: x2apic entry ignored
ACPI: x2apic entry ignored
ACPI: x2apic entry ignored
ACPI: x2apic entry ignored
IOAPIC[0]: apic_id 0, version 17, address 0xfec00000, GSI 0-23
ACPI: INT_SRC_OVR (bus 0 bus_irq 4 global_irq 4 dfl dfl)
ACPI: Using ACPI (MADT) for SMP configuration information
TSC deadline timer available
CPU topo: Max. logical packages:   1
CPU topo: Max. logical dies:       1
CPU topo: Max. dies per package:   1
CPU topo: Max. threads per core:   1
CPU topo: Num. cores per package:     1
CPU topo: Num. threads per package:   1
CPU topo: Allowing 1 present CPUs plus 0 hotplug CPUs
[mem 0x40000000-0xe7ffffff] available for PCI devices
clocksource: refined-jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645519600211568 ns
setup_percpu: NR_CPUS:64 nr_cpumask_bits:1 nr_cpu_ids:1 nr_node_ids:1
percpu: Embedded 55 pages/cpu s193512 r0 d31768 u2097152
Kernel command line: console=ttyS0,115200
random: crng init done
Dentry cache hash table entries: 131072 (order: 8, 1048576 bytes, linear)
Inode-cache hash table entries: 65536 (order: 7, 524288 bytes, linear)
Built 1 zonelists, mobility grouping on.  Total pages: 262047
mem auto-init: stack:all(zero), heap alloc:off, heap free:off
Memory: 986228K/1048188K available (16384K kernel code, 2094K rwdata, 3780K rodata, 2724K init, 1176K bss, 61704K reserved, 0K cma-reserved)
SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
ftrace: allocating 40352 entries in 158 pages
ftrace: allocated 158 pages with 5 groups
rcu: Hierarchical RCU implementation.
rcu: 	RCU event tracing is enabled.
rcu: 	RCU restricting CPUs from NR_CPUS=64 to nr_cpu_ids=1.
	Rude variant of Tasks RCU enabled.
	Tracing variant of Tasks RCU enabled.
rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
RCU Tasks Rude: Setting shift to 0 and lim to 1 rcu_task_cb_adjust=1.
RCU Tasks Trace: Setting shift to 0 and lim to 1 rcu_task_cb_adjust=1.
NR_IRQS: 4352, nr_irqs: 32, preallocated irqs: 0
rcu: srcu_init: Setting srcu_struct sizes based on contention.
Console: colour dummy device 80x25
printk: legacy console [ttyS0] enabled
ACPI: Core revision 20240322
APIC: Switch to symmetric I/O mode setup
tsc: Unable to calibrate against PIT
tsc: using PMTIMER reference calibration
tsc: Detected 3175.586 MHz processor
clocksource: tsc-early: mask: 0xffffffffffffffff max_cycles: 0x2dc63353a33, max_idle_ns: 440795298405 ns
Calibrating delay loop (skipped), value calculated using timer frequency.. 6351.17 BogoMIPS (lpj=12702344)
x86/cpu: User Mode Instruction Prevention (UMIP) activated
Last level iTLB entries: 4KB 64, 2MB 8, 4MB 8
Last level dTLB entries: 4KB 64, 2MB 0, 4MB 0, 1GB 4
Spectre V1 : Mitigation: usercopy/swapgs barriers and __user pointer sanitization
Spectre V2 : Spectre BHI mitigation: SW BHB clearing on vm exit
Spectre V2 : Spectre BHI mitigation: SW BHB clearing on syscall
Spectre V2 : Mitigation: Enhanced / Automatic IBRS
Spectre V2 : Spectre v2 / SpectreRSB mitigation: Filling RSB on context switch
Spectre V2 : Spectre v2 / PBRSB-eIBRS: Retire a single CALL on VMEXIT
RETBleed: Mitigation: Enhanced IBRS
Spectre V2 : mitigation: Enabling conditional Indirect Branch Prediction Barrier
Speculative Store Bypass: Mitigation: Speculative Store Bypass disabled via prctl
MMIO Stale Data: Mitigation: Clear CPU buffers
SRBDS: Unknown: Dependent on hypervisor status
x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
x86/fpu: Supporting XSAVE feature 0x008: 'MPX bounds registers'
x86/fpu: Supporting XSAVE feature 0x010: 'MPX CSR'
x86/fpu: Supporting XSAVE feature 0x200: 'Protection Keys User registers'
x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
x86/fpu: xstate_offset[3]:  832, xstate_sizes[3]:   64
x86/fpu: xstate_offset[4]:  896, xstate_sizes[4]:   64
x86/fpu: xstate_offset[9]:  960, xstate_sizes[9]:    8
x86/fpu: Enabled xstate features 0x21f, context size is 968 bytes, using 'compacted' format.
Freeing SMP alternatives memory: 40K
pid_max: default: 32768 minimum: 301
stackdepot: allocating hash table of 65536 entries via kvcalloc
Mount-cache hash table entries: 2048 (order: 2, 16384 bytes, linear)
Mountpoint-cache hash table entries: 2048 (order: 2, 16384 bytes, linear)
smpboot: CPU0: Intel(R) Xeon(R) W-1290 CPU @ 3.20GHz (family: 0x6, model: 0xa5, stepping: 0x5)
Performance Events: Skylake events, 32-deep LBR, full-width counters, Intel PMU driver.
... version:                2
... bit width:              48
... generic registers:      4
... value mask:             0000ffffffffffff
... max period:             00007fffffffffff
... fixed-purpose events:   3
... event mask:             000000070000000f
signal: max sigframe size: 3232
rcu: Hierarchical SRCU implementation.
rcu: 	Max phase no-delay instances is 1000.
smp: Bringing up secondary CPUs ...
smp: Brought up 1 node, 1 CPU
smpboot: Total of 1 processors activated (6351.17 BogoMIPS)
devtmpfs: initialized
x86/mm: Memory block size: 128MB
clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
futex hash table entries: 256 (order: 2, 16384 bytes, linear)
NET: Registered PF_NETLINK/PF_ROUTE protocol family
audit: initializing netlink subsys (disabled)
thermal_sys: Registered thermal governor 'step_wise'
thermal_sys: Registered thermal governor 'user_space'
audit: type=2000 audit(1719019288.008:1): state=initialized audit_enabled=0 res=1
cpuidle: using governor ladder
cpuidle: using governor menu
PCI: ECAM [mem 0xe8000000-0xe80fffff] (base 0xe8000000) for domain 0000 [bus 00-00]
PCI: ECAM [mem 0xe8000000-0xe80fffff] reserved as E820 entry
PCI: Using configuration type 1 for base access
raid6: avx2x4   gen() 52757 MB/s
raid6: avx2x2   gen() 54675 MB/s
raid6: avx2x1   gen() 44810 MB/s
raid6: using algorithm avx2x2 gen() 54675 MB/s
raid6: .... xor() 32660 MB/s, rmw enabled
raid6: using avx2x2 recovery algorithm
ACPI: Added _OSI(Module Device)
ACPI: Added _OSI(Processor Device)
ACPI: Added _OSI(3.0 _SCP Extensions)
ACPI: Added _OSI(Processor Aggregator Device)
ACPI: 1 ACPI AML tables successfully acquired and loaded
ACPI: _OSC evaluation for CPUs failed, trying _PDC
ACPI: Interpreter enabled
ACPI: PM: (supports S0 S5)
ACPI: Using IOAPIC for interrupt routing
PCI: Using host bridge windows from ACPI; if necessary, use "pci=nocrs" and report a bug
PCI: Using E820 reservations for host bridge windows
ACPI: PCI Root Bridge [PC00] (domain 0000 [bus 00])
acpi PNP0A08:00: _OSC: OS supports [ExtendedConfig ASPM ClockPM Segments HPX-Type3]
acpi PNP0A08:00: PCIe port services disabled; not requesting _OSC control
acpi PNP0A08:00: _OSC: platform retains control of PCIe features (AE_NOT_FOUND)
PCI host bridge to bus 0000:00
pci_bus 0000:00: root bus resource [mem 0xe8000000-0xe80fffff]
pci_bus 0000:00: root bus resource [mem 0xc0000000-0xe7ffffff window]
pci_bus 0000:00: root bus resource [mem 0x100000000-0x7effffffff window]
pci_bus 0000:00: root bus resource [io  0x0000-0x0cf7 window]
pci_bus 0000:00: root bus resource [io  0x0d00-0xffff window]
pci_bus 0000:00: root bus resource [bus 00]
pci 0000:00:00.0: [8086:0d57] type 00 class 0x060000 conventional PCI endpoint
pci 0000:00:01.0: [1af4:1043] type 00 class 0xffff00 conventional PCI endpoint
pci 0000:00:01.0: BAR 0 [mem 0x7efff80000-0x7effffffff 64bit]
pci 0000:00:02.0: [1af4:1041] type 00 class 0x020000 conventional PCI endpoint
pci 0000:00:02.0: BAR 0 [mem 0x7efff00000-0x7efff7ffff 64bit]
pci 0000:00:03.0: [1af4:1044] type 00 class 0xffff00 conventional PCI endpoint
pci 0000:00:03.0: BAR 0 [mem 0x7effe80000-0x7effefffff 64bit]
ACPI: Unable to map lapic to logical cpu number
ACPI: Unable to map lapic to logical cpu number
ACPI: Unable to map lapic to logical cpu number
iommu: Default domain type: Translated
iommu: DMA domain TLB invalidation policy: lazy mode
SCSI subsystem initialized
pps_core: LinuxPPS API ver. 1 registered
pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
PTP clock support registered
PCI: Using ACPI for IRQ routing
vgaarb: loaded
clocksource: Switched to clocksource tsc-early
pnp: PnP ACPI init
system 00:00: [mem 0xe8000000-0xe80fffff] has been reserved
pnp: PnP ACPI: found 2 devices
clocksource: acpi_pm: mask: 0xffffff max_cycles: 0xffffff, max_idle_ns: 2085701024 ns
NET: Registered PF_INET protocol family
IP idents hash table entries: 16384 (order: 5, 131072 bytes, linear)
tcp_listen_portaddr_hash hash table entries: 512 (order: 1, 8192 bytes, linear)
Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
TCP established hash table entries: 8192 (order: 4, 65536 bytes, linear)
TCP bind hash table entries: 8192 (order: 6, 262144 bytes, linear)
TCP: Hash tables configured (established 8192 bind 8192)
UDP hash table entries: 512 (order: 2, 16384 bytes, linear)
UDP-Lite hash table entries: 512 (order: 2, 16384 bytes, linear)
NET: Registered PF_UNIX/PF_LOCAL protocol family
pci_bus 0000:00: resource 4 [mem 0xe8000000-0xe80fffff]
pci_bus 0000:00: resource 5 [mem 0xc0000000-0xe7ffffff window]
pci_bus 0000:00: resource 6 [mem 0x100000000-0x7effffffff window]
pci_bus 0000:00: resource 7 [io  0x0000-0x0cf7 window]
pci_bus 0000:00: resource 8 [io  0x0d00-0xffff window]
PCI: CLS 0 bytes, default 64
Unpacking initramfs...
RAPL PMU: API unit is 2^-32 Joules, 0 fixed counters, 10737418240 ms ovfl timer
platform rtc_cmos: registered platform RTC device (no PNP device found)
workingset: timestamp_bits=46 max_order=18 bucket_order=0
fuse: init (API version 7.40)
SGI XFS with security attributes, no debug enabled
9p: Installing v9fs 9p2000 file system support
xor: automatically using best checksumming function   avx       
Block layer SCSI generic (bsg) driver version 0.4 loaded (major 252)
input: Power Button as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0C:00/input/input0
ACPI: button: Power Button [PWRB]
virtio-pci 0000:00:01.0: enabling device (0000 -> 0002)
virtio-pci 0000:00:02.0: enabling device (0000 -> 0002)
virtio-pci 0000:00:03.0: enabling device (0000 -> 0002)
Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled
00:01: ttyS0 at I/O 0x3f8 (irq = 24, base_baud = 115200) is a 16550A
virtio_console virtio0: Error -28 initializing vqs
virtio_console virtio0: probe with driver virtio_console failed with error -28
virtio_rng virtio2: probe with driver virtio_rng failed with error -28
loop: module loaded
zram: Added device: zram0
tun: Universal TUN/TAP device driver, 1.6
virtio_net virtio1: probe with driver virtio_net failed with error -28
mkiss: AX.25 Multikiss, Hans Albas PE1AYX
i8042: PNP: No PS/2 controller found.
intel_pstate: CPU model not supported
xt_time: kernel timezone is -0000
NET: Registered PF_INET6 protocol family
Segment Routing with IPv6
In-situ OAM (IOAM) with IPv6
sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
NET: Registered PF_PACKET protocol family
Bridge firewalling registered
NET: Registered PF_NETROM protocol family
NET: Registered PF_AX25 protocol family
8021q: 802.1Q VLAN Support v1.8
9pnet: Installing 9P2000 support
NET: Registered PF_VSOCK protocol family
IPI shorthand broadcast: enabled
sched_clock: Marking stable (380036390, 614361)->(421870366, -41219615)
zswap: loaded using pool lzo/zsmalloc
Btrfs loaded, zoned=no, fsverity=no
clk: Disabling unused clocks
Freeing initrd memory: 16220K
Freeing unused kernel image (initmem) memory: 2724K
Write protecting the kernel read-only data: 20480k
Freeing unused kernel image (rodata/data gap) memory: 316K
Run /init as init process
Cannot find device "eth0"
[?2004h(none):/# tsc: Refined TSC clocksource calibration: 3191.982 MHz
clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x2e02b392dae, max_idle_ns: 440795287017 ns
clocksource: Switched to clocksource tsc
```

**Comment by larsks** [comment] 2024-06-22 01:23
NB: The same errors appear to prevent virtio network devices from working as well.

**Comment by larsks** [comment] 2024-06-22 01:33
I apologize; I didn't realize OBS lagged so far behind the current release. My impressions was that the release pipeline included automatically building packages on OBS.

I have downloaded cloud-hyperversion version v39.0 from https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v39.0 and confirmed that it produces the same behavior.

**Comment by liuw** [comment] 2024-06-22 03:29
You use two different kernels for CH and QEMU. Why is that?

**Comment by larsks** [comment] 2024-06-22 12:06
They are the same kernel. I use the bzimage with QEMU, but ch 38 was unable to boot it.

**Comment by liuw** [comment] 2024-06-24 20:12
I quickly went over the code. Error number 28 is ENOSPC in Linux kernel. I couldn't quickly identify where it could come from in the probing path. The log from CH doesn't look abnormal other than the IO port accesses. I don't think they are relevant because virito-pci at that stage relies on MMIO accesses to function.

@larsks can you share your guest kernel config?

**Comment by larsks** [comment] 2024-06-24 21:03
Sure; I've attached it here.

[config.txt](https://github.com/user-attachments/files/15961229/config.txt)

I'm building from kernel commit `4545981f33be5f04ee8dd43397ea29c37337dd03` (which was `master` on 6/21).

**Comment by liuw** [comment] 2024-06-24 22:43
My quick test shows that if I build the guest kernel with your config, it doesn't work; but if I build the same kernel with the reference config (see README), the guest works just fine. I have yet to work out which Kconfig options are critical.

When it doesn't work, I cannot reproduce what you saw either. I just couldn't get any output on the console.

I would suggest you use the reference kernel config for now, unless you have a very compelling reason not to.

**Comment by liuw** [comment] 2024-07-02 23:59
Closing this since it is not really a bug. Rather I think it is a configuration issue on the guest side.

**Closed by liuw** 2024-07-02 23:59 UTC
