### ISSUE TITLE
Corrupted disk image causes block thread to hang

### ISSUE THREAD

**Issue by liuw** [cloud-hypervisor/cloud-hypervisor#2424] opened 2021-03-23 18:05 UTC
Passing a corrupted disk image caused Cloud Hypervisor's block thread to hang.

```
cloud-hypervisor: 11.342521081s: <_disk0_q0> ERROR:virtio-devices/src/block.rs:316 -- Failed to process queue (submit): RequestParsing(DescriptorChainTooShort)
```

I think the expected behaviour is to allow the guest to continue and discover the its file system is corrupted. That's what would happen on a real machine.

@russell-islam Can you describe how you accidentally corrupted the image?

**Comment by russell-islam** [comment] 2021-03-23 18:19
I don't actually remember but I think I have mounted the disk, chroot it, and changed the root password. Then without unmounting the disk I have created a guest with the disk. That's the only scenario I can think of.

**Comment by rbradford** [comment] 2021-03-24 14:44
I don't really know how a corrupted disk could get to a state where the guest is generating a descriptor chain that is too short. Sadly there is no way for us to tell the guest that we couldn't process their request as this error means that the guest has not given us a status block to write any status in to.

Currently whenever we hit an error we can't report to the guest we log an error and the block thread exits. We could change the behaviour so that on an unreportable error we don't exit but that could potentially lead to further data loss.

**Comment by sboeuf** [comment] 2021-03-24 14:56
@rbradford 

>Currently whenever we hit an error we can't report to the guest we log an error and the block thread exits. We could change the behaviour so that on an unreportable error we don't exit but that could potentially lead to further data loss.

I guess one alternative is to avoid exiting the thread but still report the error to the virtio driver. This is a tradeoff that would keep the virtio device alive but the would stop using it as it would be unusable.

**Comment by rbradford** [comment] 2021-03-24 15:22
Since we can't report an error to the driver because we don't have a status field we'd need to it it via `DEVICE_NEEDS_RESET` driver status bit. Sadly the Linux driver never checks for this bit.

**Comment by sboeuf** [comment] 2021-03-24 15:43
But I thought we could report `VIRTIO_BLK_S_IOERR` through the virtio queue?
There's a status part in the virtio-blk descriptors.

**Comment by rbradford** [comment] 2021-03-24 15:46
> But I thought we could report `VIRTIO_BLK_S_IOERR` through the virtio queue?
> There's a status part in the virtio-blk descriptors.

See my earlier comment, we generate this error message because there is no status descriptor.

**Comment by liuw** [comment] 2021-03-24 16:52
How would QEMU handle this? We can perhaps get inspiration from QEMU?

From a user experience's point of view, not getting a chance to fix their corrupted disk is not ideal. Although the disk can be mounted and fixed on the host, they wouldn't want the host administrators to access their data.

**Comment by russell-islam** [comment] 2021-03-24 19:21
Yesterday I was able to reproduce the issue. I tried to loop mount the root partition, normally it should not take more than a second but it took almost 10 seconds to mount. Then I have changed the root password by doing the chroot. After unmounting the disk I tried to boot. The boot was stuck after getting the DescriptorChainTooShort error.  Then I killed the process. Remounted the disk, Deleted the NvVars from the /boot, then I was able to boot successfully again.

**Comment by liuw** [comment] 2021-03-24 20:19
@russell-islam Please save a copy of the corrupted disk when you see it again. It would be useful for reproducing this issue.

**Comment by rbradford** [comment] 2021-03-26 15:39
Are you using `--initramfs` in your CH command line?

**Comment by liuw** [comment] 2021-03-26 15:51
We were using OVMF (the one used in CI), not direct kernel boot. There is no `--initramfs` in the command line.

**Comment by rbradford** [comment] 2021-03-26 15:53
@liuw I thought so, we've seen two other reports where initramfs was involved and we think we've found and address calculation issue for initramfs that does seem to reproduce this error. However I suspect there are multiple issues involved.

**Comment by rbradford** [comment] 2021-03-26 16:02
Do you remember how much RAM was assigned to the VM?

**Comment by liuw** [comment] 2021-03-26 16:05
IIRC we assigned 4G to the guest. @russell-islam correct me if I'm wrong.

**Comment by russell-islam** [comment] 2021-03-26 16:42
@liuw You are right we have used 4G memory. @rbradford  FYI I have used the following command.

sudo ./cloud-hypervisor/target/release/cloud-hypervisor --kernel OVMF_MY_BUILD.fd --disk path=/home/muislam/dev/chris-images/mariner-clh.raw --cpus boot=4 --memory size=4G --serial tty --console off --seccomp false --net "tap=,mac=,ip=,mask="

**Closed** 2021-03-29 15:37 UTC
