### ISSUE TITLE
Failed to load guest kernel after cloud-hypervisor number reach a threshold

### ISSUE THREAD

**Issue by arronwy** [cloud-hypervisor/cloud-hypervisor#1175] opened 2020-05-14 06:44 UTC
I tried to launch secure containers with cloud-hypervisor as the default vmm. After launch the numbers of secure container reach a threshold, it will failed to start new contianers with following error:

`FATA[0000] run pod sandbox failed: rpc error: code = Unknown desc = failed to start sandbox container: failed to create containerd task: error: 500  reason: VmBoot(VmBoot(KernelLoad(Elf(ReadKernelImage)))): unknown
`

I also tried with latest cloud-hypervsior master, seems also have the same issue.
In a Intel NUC with 8G memory, it can launch about 30 pods even it still have many available memory:
```
ps -ef|grep cloud-hypervisor|wc -l
31

free -m
              total        used        free      shared  buff/cache   available
 Mem:           7840         926         422        4261        6491        2354
```

failed launch cloud-hypervisor log:

sudo cat /run/vc/vm/808cf66af587314bbe9af2d00526073e1766a006f6f330778c839a63ddbb8e47/clh.log

cloud-hypervisor: 29.182481ms: INFO:vmm/src/memory_manager.rs:727 -- Created userspace mapping: 0 -> 7ffb28000000 80000000
cloud-hypervisor: 29.602762ms: ERROR:vmm/src/config.rs:1274 -- Use of backing file ('--memory file=') is deprecated. Use the 'shared' and 'hugepages' controls.
cloud-hypervisor: 29.978979ms: INFO:vmm/src/vm.rs:347 -- Begin open kernel file
cloud-hypervisor: 30.10426ms: INFO:vmm/src/vm.rs:352 -- Open kernel file success
cloud-hypervisor: 40.668918ms: INFO:vmm/src/memory_manager.rs:727 -- Created userspace mapping: 7fc0000000 -> 7ffae8000000 40000000
cloud-hypervisor: 79.779629ms: INFO:vmm/src/memory_manager.rs:727 -- Created userspace mapping: 7fb8000000 -> 7ffae0000000 8000000
cloud-hypervisor: 100.095275ms: INFO:vmm/src/vm.rs:411 -- vm new success
cloud-hypervisor: 100.230706ms: INFO:vmm/src/vm.rs:983 -- vm boot cpu_manager
cloud-hypervisor: 100.451483ms: INFO:vmm/src/vm.rs:495 -- begin load kernel File { fd: 22, path: "/opt/kata/share/kata-containers/vmlinux-virtio-fs-dev-73-virtiofs", read: true, write: false }

In a server with 96G memory, it can launch about 310 pods, after that when we launch new pods cloud-hypervisor will have the same load error, even we still have many free memory:
free -m
              total        used        free      shared  buff/cache   available
Mem:          95086       16139       30334       47458       48613       31181

**Comment by rbradford** [comment] 2020-05-14 08:21
What size of RAM are you trying to assign to the VM?

**Comment by arronwy** [comment] 2020-05-14 08:26
> What size of RAM are you trying to assign to the VM?
I used the default config of kata to allocate 2048 MiB to guest, the real host memory used by guest is about ~150MiB.

**Comment by rbradford** [comment] 2020-05-14 08:35
So on your NUC you should expect to be able to run 4 (8 / 2) So you're intentionally overcommiting?

If you do that i'm not surprised that it fails when it tries to write to load the kernel into guest RAM. Overcommit will lead to strange failures at a future point in time.

**Comment by arronwy** [comment] 2020-05-14 08:51
Yes, memory is overcommiting by default,  I also tried in server with 96G memory, it will have same error when we have 30G free memory.

**Comment by rbradford** [comment] 2020-05-14 08:54
@arronwy There is some documentation about overcommit here: https://www.kernel.org/doc/Documentation/vm/overcommit-accounting

"free" is not a good representation of the free memory.

**Comment by sameo** [comment] 2020-05-14 09:01
@arronwy You should not base your assumptions on how many more VMs you can squeeze into the device from the `free` output. `free` telling you that there is 2 GB of available memory does not guarantee that your next 2GB VM allocation will succeed.

If you're trying to measure practical density, I'd advice to build a baseline:

- Use smaller VMs.
- Define a mostly idle workload, definitely not memory bound. For example an alpine image that can answer pings.
- Define the density threshold as the number of VMs that you can launch and run, until the average response latency of all running VMs goes above a certain number.

Then your density results are a function of your workload, the VM size, and the max latency.

**Comment by arronwy** [comment] 2020-05-14 09:22
> @arronwy You should not base your assumptions on how many more VMs you can squeeze into the device from the `free` output. `free` telling you that there is 2 GB of available memory does not guarantee that your next 2GB VM allocation will succeed.
> 
> If you're trying to measure practical density, I'd advice to build a baseline:
> 
> * Use smaller VMs.

we use kata latest 1.11.0 release and compare different lower level hypervisor with the same kernel and rootfs. 

> * Define a mostly idle workload, definitely not memory bound. For example an alpine image that can answer pings.

Yes, currently we did not run workload containers in our guest, next we will add some workload to test some performance data

> * Define the density threshold as the number of VMs that you can launch and run, until the average response latency of all running VMs goes above a certain number.
> 
> Then your density results are a function of your workload, the VM size, and the max latency.

Thanks for your suggestions, we will try follow this way

**Comment by sameo** [comment] 2020-05-14 12:45
> > @arronwy You should not base your assumptions on how many more VMs you can squeeze into the device from the `free` output. `free` telling you that there is 2 GB of available memory does not guarantee that your next 2GB VM allocation will succeed.
> > If you're trying to measure practical density, I'd advice to build a baseline:
> > 
> > * Use smaller VMs.
> 
> we use kata latest 1.11.0 release and compare different lower level hypervisor with the same kernel and rootfs.
> 

It would be interesting to get an independent baseline for Cloud Hypervisor by e.g. running 

> > * Define a mostly idle workload, definitely not memory bound. For example an alpine image that can answer pings.
> 
> Yes, currently we did not run workload containers in our guest, next we will add some workload to test some performance data
> 
> > * Define the density threshold as the number of VMs that you can launch and run, until the average response latency of all running VMs goes above a certain number.
> > 
> > Then your density results are a function of your workload, the VM size, and the max latency.
> 
> Thanks for your suggestions, we will try follow this way

**Comment by arronwy** [comment] 2020-05-15 02:19
We follow this guide https://github.com/kata-containers/documentation/blob/master/how-to/containerd-kata.md to use kata and containerd and launch pods with CRI interface. The kata version is latest 1.11.0 with cloud-hypervisor 0.7.0 and qemu 4.1.1. We use the default configuration for both cloud-hypervisor and qemu. The default configuration is 1vcpu, 2G default memory and virtio-fs as the shared fs, they also use the same guest kernel and rootfs image.

First we start pods with qemu as the vmm backend, we found the host memory used part are increased linearly, about 160MiB per pod, but shared and cached are not change too much, after we start more than 500 pods, the memory consumption reach the threshold for KSM, ksmtuned will start auto kernel same page merge, and free memory will start increase. We continue to start pods,  after free memory are just several hundred megabit, it will failed to start, the detail info as below:
```
Qemu 
100 Pods
[node-centos@lonia-cloud-dev ~]$ free -m
              total        used        free      shared  buff/cache   available
Mem:          95086       17582       76399          50        1104       76875
Swap:             0           0           0

200 Pods
[node-centos@lonia-cloud-dev ~]$ free -m
              total        used        free      shared  buff/cache   available
Mem:          95086       33642       60208         125        1235       60895
Swap:             0           0           0

300 Pods
[node-centos@lonia-cloud-dev ~]$ free -m
              total        used        free      shared  buff/cache   available
Mem:          95086       50041       43611         255        1434       44524

400 Pods
[node-centos@lonia-cloud-dev ~]$ free -m
              total        used        free      shared  buff/cache   available
Mem:          95086       66006       27421         410        1658       28556

500 Pods
[node-centos@lonia-cloud-dev ~]$ free -m
              total        used        free      shared  buff/cache   available
Mem:          95086       83005       10037         701        2042       11427

600 Pods
[node-centos@lonia-cloud-dev ~]$ free -m
              total        used        free      shared  buff/cache   available
Mem:          95086       73159       19330        1136        2597       21006

700 Pods
[node-centos@lonia-cloud-dev ~]$ free -m
              total        used        free      shared  buff/cache   available
Mem:          95086       59320       30874        3090        4891       33045

800 Pods
[node-centos@lonia-cloud-dev ~]$ free -m
              total        used        free      shared  buff/cache   available
Mem:          95086       74900       14735        3597        5450       16780

900 Pods 
[node-centos@lonia-cloud-dev ~]$ free -m
              total        used        free      shared  buff/cache   available
Mem:          95086       88522         828        3872        5736        2658

sudo crictl pods  | wc -l
893

[node-centos@lonia-cloud-dev ~]$ free -m
              total        used        free      shared  buff/cache   available
Mem:          95086       88958         323        3944        5804        2093

final error:
FATA[0021] run pod sandbox failed: rpc error: code = Unknown desc = failed to start sandbox container: 
failed to create containerd task: Failed to check if grpc server is working: rpc error: code = Unavailable desc = transport is closing: unknown
``` 

When we start pods with cloud hypervisor as the vmm backend,  the host memory shared part are increased linearly, after launch about 310 pods, it will have failed to load guest kernel error:
```
cloud hypervisor
100 Pods
[node-centos@lonia-cloud-dev scripts]$ free -m
              total        used        free      shared  buff/cache   available
Mem:          95086        6349       71961       15825       16776       72318

200 Pods
[node-centos@lonia-cloud-dev scripts]$ free -m
              total        used        free      shared  buff/cache   available
Mem:          95086       11215       51198       31640       32672       51773
300 Pods
[node-centos@lonia-cloud-dev scripts]$ free -m
              total        used        free      shared  buff/cache   available
Mem:          95086       16139       30334       47458       48613       31181

sudo crictl pods  | wc -l
310
FATA[0000] run pod sandbox failed: rpc error: code = Unknown desc = failed to start sandbox container: 
failed to create containerd task: error: 500  reason: VmBoot(VmBoot(KernelLoad(Elf(ReadKernelImage)))): unknown
```

We also found cloud hypervisor open the guest kernel is not closed due to kernel file object is saved in vm struct, but this is not the root cause for failed to continue load guest kernel:
```
sudo lsof|grep vmlinux
cloud-hyp 20585                   root   22r      REG                8,2   24826208   14419844 /opt/kata/share/kata-containers/vmlinux-virtio-fs-dev-73-virtiofs
vmm       20585 20586             root   22r      REG                8,2   24826208   14419844 /opt/kata/share/kata-containers/vmlinux-virtio-fs-dev-73-virtiofs
http-serv 20585 20587             root   22r      REG                8,2   24826208   14419844 /opt/kata/share/kata-containers/vmlinux-virtio-fs-dev-73-virtiofs
```
New processes for each pod
```
cloud-hypervisor
root     25953     1  2 10:15 ?        00:00:00 /bin/containerd-shim-kata-v2 -namespace k8s.io -address /run/containerd/containerd.sock -publish-binary /usr/bin/containerd -id a24f1c4e317ee8c74ab91eb2fbdf3e180b4365e2cfe07d601e9e2b1a96242974 -debug
root     25965 25953  0 10:15 ?        00:00:00 /opt/kata/bin/virtiofsd -f -o cache=always -o no_posix_lock -o source=/run/kata-containers/shared/sandboxes/a24f1c4e317ee8c74ab91eb2fbdf3e180b4365e2cfe07d601e9e2b1a96242974 -o vhost_user_socket=/run/vc/vm/a24f1c4e317ee8c74ab91eb2fbdf3e180b4365e2cfe07d601e9e2b1a96242974/virtiofsd.sock
root     25967 25953 11 10:15 ?        00:00:02 /opt/kata/bin/cloud-hypervisor --api-socket /run/vc/vm/a24f1c4e317ee8c74ab91eb2fbdf3e180b4365e2cfe07d601e9e2b1a96242974/clh-api.sock -vvv --log-file /run/vc/vm/a24f1c4e317ee8c74ab91eb2fbdf3e180b4365e2cfe07d601e9e2b1a96242974/clh.log

qemu
root     26319     1  1 10:17 ?        00:00:00 /bin/containerd-shim-kata-v2 -namespace k8s.io -address /run/containerd/containerd.sock -publish-binary /usr/bin/containerd -id 2202c6fec069a33763f7af85b18d36a075f4b7a004279713caf905225b4d28d6 -debug
root     26330 26319  0 10:17 ?        00:00:00 /opt/kata/bin/virtiofsd --fd=3 -o source=/run/kata-containers/shared/sandboxes/2202c6fec069a33763f7af85b18d36a075f4b7a004279713caf905225b4d28d6 -o cache=always --syslog -o no_posix_lock -f
root     26335     1  7 10:17 ?        00:00:00 /opt/kata/bin/qemu-virtiofs-system-x86_64 -name sandbox-2202c6fec069a33763f7af85b18d36a075f4b7a004279713caf905225b4d28d6 -uuid 0c1461de-72b0-44b7-b95b-4085927c1335 -machine pc,accel=kvm,kernel_irqchip,nvdimm -cpu host -qmp unix:/run/vc/vm/2202c6fec069a33763f7af85b18d36a075f4b7a004279713caf905225b4d28d6/qmp.sock,server,nowait -m 2048M,slots=10,maxmem=8864M -device pci-bridge,bus=pci.0,id=pci-bridge-0,chassis_nr=1,shpc=on,addr=2,romfile= -device virtio-serial-pci,disable-modern=false,id=serial0,romfile= -device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/vc/vm/2202c6fec069a33763f7af85b18d36a075f4b7a004279713caf905225b4d28d6/console.sock,server,nowait -device nvdimm,id=nv0,memdev=mem0 -object memory-backend-file,id=mem0,mem-path=/opt/kata/share/kata-containers/kata-containers-image_clearlinux_1.11.0_agent_80de213dde.img,size=134217728 -device virtio-scsi-pci,id=scsi0,disable-modern=false,romfile= -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0,romfile= -device virtserialport,chardev=charch0,id=channel0,name=agent.channel.0 -chardev socket,id=charch0,path=/run/vc/vm/2202c6fec069a33763f7af85b18d36a075f4b7a004279713caf905225b4d28d6/kata.sock,server,nowait -chardev socket,id=char-33e5f1575ba1185b,path=/run/vc/vm/2202c6fec069a33763f7af85b18d36a075f4b7a004279713caf905225b4d28d6/vhost-fs.sock -device vhost-user-fs-pci,chardev=char-33e5f1575ba1185b,tag=kataShared,cache-size=1024M,romfile= -global kvm-pit.lost_tick_policy=discard -vga none -no-user-config -nodefaults -nographic -daemonize -object memory-backend-file,id=dimm1,size=2048M,mem-path=/dev/shm,share=on -numa node,memdev=dimm1 -kernel /opt/kata/share/kata-containers/vmlinuz-virtio-fs-dev-73-virtiofs -append tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k console=hvc0 console=hvc1 iommu=off cryptomgr.notests net.ifnames=0 pci=lastbus=0 root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro ro rootfstype=ext4 quiet systemd.show_status=false panic=1 nr_cpus=8 agent.use_vsock=false systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket scsi_mod.scan=none -pidfile /run/vc/vm/2202c6fec069a33763f7af85b18d36a075f4b7a004279713caf905225b4d28d6/pid -smp 1,cores=1,threads=1,sockets=8,maxcpus=8
```

**Comment by arronwy** [comment] 2020-06-05 05:18
we found this issue may related to virtio-fs. On a NUC with 8G memory, we use kata 1.11.0 release default configuration with 1vCPU and 2G memory for each VM.

For Qemu with virtio-9p as the sharedfs, we can launch about 74 secure container and consume most of the host memory:
```
[Hypervisor]
  MachineType = "pc"
  Version = "QEMU emulator version 4.1.1 (kata-static)\nCopyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers"
  Path = "/opt/kata/bin/qemu-system-x86_64"
  BlockDeviceDriver = "virtio-scsi"
  EntropySource = "/dev/urandom"
  SharedFS = "virtio-9p"
  VirtioFSDaemon = "/opt/kata/bin/virtiofsd"
  Msize9p = 8192
  MemorySlots = 10
  PCIeRootPort = 0
  HotplugVFIOOnRootBus = false
  Debug = false
  UseVSock = false
```
For Qemu with virtio-fs as the sharedfs, we can only launch about 35 secure container and still have many host memory when failed to launch new VM:
```
$ free -m
              total        used        free      shared  buff/cache   available
Mem:           7840        1800        1594        3871        4445        1970
Swap:          4095          21        4074

[Hypervisor]
  MachineType = "pc"
  Version = "QEMU emulator version 4.1.0 (kata-static)\nCopyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers"
  Path = "/opt/kata/bin/qemu-virtiofs-system-x86_64"
  BlockDeviceDriver = "virtio-scsi"
  EntropySource = "/dev/urandom"
  SharedFS = "virtio-fs"
  VirtioFSDaemon = "/opt/kata/bin/virtiofsd"
  Msize9p = 8192
  MemorySlots = 10
  PCIeRootPort = 0
  HotplugVFIOOnRootBus = false
  Debug = false
  UseVSock = false
```

For the guest rootfs, they both use nvdimm device, the major difference is sharedfs for container image. 
```
virtio-fs:
qemu-virtiofs-system-x86_64 -name sandbox-2202c6fec069a33763f7af85b18d36a075f4b7a004279713caf905225b4d28d6 
-uuid 0c1461de-72b0-44b7-b95b-4085927c1335 
-machine pc,accel=kvm,kernel_irqchip,nvdimm -cpu host 
-qmp unix:/run/vc/vm/2202c6fec069a33763f7af85b18d36a075f4b7a004279713caf905225b4d28d6/qmp.sock,server,nowait 
-m 2048M,slots=10,maxmem=8864M 
-device pci-bridge,bus=pci.0,id=pci-bridge-0,chassis_nr=1,shpc=on,addr=2,romfile= -device virtio-serial-pci,disable-modern=false,id=serial0,romfile= 
-device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/vc/vm/2202c6fec069a33763f7af85b18d36a075f4b7a004279713caf905225b4d28d6/console.sock,server,nowait 
-device nvdimm,id=nv0,memdev=mem0 -object memory-backend-file,id=mem0,mem-path=/opt/kata/share/kata-containers/kata-containers-image_clearlinux_1.11.0_agent_80de213dde.img,size=134217728 
-device virtio-scsi-pci,id=scsi0,disable-modern=false,romfile= -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0,romfile= 
-device virtserialport,chardev=charch0,id=channel0,name=agent.channel.0 
-chardev socket,id=charch0,path=/run/vc/vm/2202c6fec069a33763f7af85b18d36a075f4b7a004279713caf905225b4d28d6/kata.sock,server,nowait 
-chardev socket,id=char-33e5f1575ba1185b,path=/run/vc/vm/2202c6fec069a33763f7af85b18d36a075f4b7a004279713caf905225b4d28d6/vhost-fs.sock 
*************************************
-device vhost-user-fs-pci,chardev=char-33e5f1575ba1185b,tag=kataShared,cache-size=1024M,romfile= 
*************************************
-global kvm-pit.lost_tick_policy=discard -vga none -no-user-config -nodefaults -nographic -daemonize -object memory-backend-file,id=dimm1,size=2048M,mem-path=/dev/shm,share=on -numa node,memdev=dimm1 
-kernel /opt/kata/share/kata-containers/vmlinuz-virtio-fs-dev-73-virtiofs -append tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k console=hvc0 console=hvc1 iommu=off cryptomgr.notests net.ifnames=0 pci=lastbus=0 root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro ro rootfstype=ext4 quiet systemd.show_status=false panic=1 nr_cpus=8 agent.use_vsock=false systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket scsi_mod.scan=none -pidfile /run/vc/vm/2202c6fec069a33763f7af85b18d36a075f4b7a004279713caf905225b4d28d6/pid 
-smp 1,cores=1,threads=1,sockets=8,maxcpus=8

virtio-9p
qemu-system-x86_64 -name sandbox-b600056f73e49e38eb4a660498916f7aa223954c1316d2e5c10e5d45bfe29af9 
-uuid 938e88f6-bbfa-4f21-895d-ab4a4a1dedae 
-machine pc,accel=kvm,kernel_irqchip,nvdimm -cpu host 
-qmp unix:/run/vc/vm/b600056f73e49e38eb4a660498916f7aa223954c1316d2e5c10e5d45bfe29af9/qmp.sock,server,nowait 
-m 2048M,slots=10,maxmem=8864M 
-device pci-bridge,bus=pci.0,id=pci-bridge-0,chassis_nr=1,shpc=on,addr=2,romfile= -device virtio-serial-pci,disable-modern=false,id=serial0,romfile= 
-device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/vc/vm/b600056f73e49e38eb4a660498916f7aa223954c1316d2e5c10e5d45bfe29af9/console.sock,server,nowait 
-device nvdimm,id=nv0,memdev=mem0 -object memory-backend-file,id=mem0,mem-path=/opt/kata/share/kata-containers/kata-containers-image_clearlinux_1.11.0_agent_80de213dde.img,size=134217728 
-device virtio-scsi-pci,id=scsi0,disable-modern=false,romfile= -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0,romfile= 
-device virtserialport,chardev=charch0,id=channel0,name=agent.channel.0 
-chardev socket,id=charch0,path=/run/vc/vm/b600056f73e49e38eb4a660498916f7aa223954c1316d2e5c10e5d45bfe29af9/kata.sock,server,nowait 
*************************************
-device virtio-9p-pci,disable-modern=false,fsdev=extra-9p-kataShared,mount_tag=kataShared,romfile= -fsdev local,id=extra-9p-kataShared,path=/run/kata-containers/shared/sandboxes/b600056f73e49e38eb4a660498916f7aa223954c1316d2e5c10e5d45bfe29af9,security_model=none 
*************************************
-global kvm-pit.lost_tick_policy=discard -vga none -no-user-config -nodefaults -nographic -daemonize -object memory-backend-ram,id=dimm1,size=2048M -numa node,memdev=dimm1 
-kernel /opt/kata/share/kata-containers/vmlinuz-5.4.32-73 -append tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k console=hvc0 console=hvc1 iommu=off cryptomgr.notests net.ifnames=0 pci=lastbus=0 root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro ro rootfstype=ext4 quiet systemd.show_status=false panic=1 nr_cpus=8 agent.use_vsock=false systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket scsi_mod.scan=none -pidfile /run/vc/vm/b600056f73e49e38eb4a660498916f7aa223954c1316d2e5c10e5d45bfe29af9/pid 
-smp 1,cores=1,threads=1,sockets=8,maxcpus=8
```

**Comment by sboeuf** [comment] 2020-06-05 07:22
@arronwy could you run the same test for QEMU with virtio-fs. It would be easier to compare it with Cloud-Hypervisor, as I suspect virtio-fs (because of vhost-user) consume more memory on the host.

**Comment by arronwy** [comment] 2020-06-05 07:49
> @arronwy could you run the same test for QEMU with virtio-fs. It would be easier to compare it with Cloud-Hypervisor, as I suspect virtio-fs (because of vhost-user) consume more memory on the host.

Above data is for Qemu with virtio-9p (launch 74 pods) and Qemu with virtio-fs (launch 35 pods).
Cloud Hypervisor default use virtio-fs and have similar results with Qemu with virtio-fs.

**Comment by sboeuf** [comment] 2020-06-05 08:00
You just confirmed that this is tied to virtio-fs. And the fact that Cloud-Hypervisor and QEMU behave the same way shows there's no issue at all IMO.

You could try to disable `dax` with an empty cache region for virtio-fs, and maybe in that case you will see better density. I'm suggesting this because without `dax`, the files are not mapped in the cache region, but instead they're copied to the virtqueues, hence each VMM should have a smaller footprint.

**Comment by arronwy** [comment] 2020-06-05 08:07
> You just confirmed that this is tied to virtio-fs. And the fact that Cloud-Hypervisor and QEMU behave the same way shows there's no issue at all IMO.

Yes, I also agree there no issue in CLH or Qemu.
> 
> You could try to disable `dax` with an empty cache region for virtio-fs, and maybe in that case you will see better density. I'm suggesting this because without `dax`, the files are not mapped in the cache region, but instead they're copied to the virtqueues, hence each VMM should have a smaller footprint.

Thanks for your suggestions, we will have a try.

**Comment by rbradford** [comment] 2020-06-05 09:11
Cool, if there is no issue with Cloud Hypervisor then we can close this issue?

**Comment by arronwy** [comment] 2020-06-05 09:38
Yes, I think we can close this issue, BTW any suggestions for track this virtio-fs related isse? Maybe in kata?

**Comment by sboeuf** [comment] 2020-06-05 10:34
Sure you can follow this in Kata, but I'm not even sure this is something that can be fixed if it's inherent to the virtio-fs design itself.

**Closed by sboeuf** 2020-06-05 10:34 UTC

**Comment by arronwy** [comment] 2020-06-18 02:51
@sameo @rbradford @sboeuf  I finally found the root cause maybe due to the default config size of /dev/shm:
```
# free -m
              total        used        free      shared  buff/cache   available
Mem:           7840         367        4657           1        2815        7189
Swap:          4095           0        4095

# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.8G     0  3.8G   0% /dev
tmpfs           785M  1.3M  783M   1% /run
/dev/sda2       234G   29G  193G  14% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/loop1       10M   10M     0 100% /snap/helm/241
/dev/loop3       92M   92M     0 100% /snap/go/5759
/dev/loop4       94M   94M     0 100% /snap/core/9066
/dev/loop2       81M   81M     0 100% /snap/kata-containers/629
/dev/loop0       92M   92M     0 100% /snap/go/5830
/dev/loop6       14M   14M     0 100% /snap/prometheus/18
/dev/loop5       55M   55M     0 100% /snap/core18/1754
/dev/loop7       98M   98M     0 100% /snap/core/9289
/dev/loop8       10M   10M     0 100% /snap/helm/244
/dev/loop9       81M   81M     0 100% /snap/kata-containers/655
/dev/sda1       511M  6.1M  505M   2% /boot/efi
tmpfs           785M     0  785M   0% /run/user/1000
```
The default maximum size of the /dev/shm filesystem is half of the total system memory, and virtio-fs mainly use /dev/shm to host shared filesystem, after we resize /dev/shm to the whole of the system memory, Qemu with virtio-fs as sharedfs backend can launch nearly the same pods as virtio-9p, and cloud hypervisor also can launch nearly the same pods.
After we launch one pod:
```
# mount |grep shm
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
shm on /run/containerd/io.containerd.grpc.v1.cri/sandboxes/dd6f84775e5d5cd555a7e998345b770721ba2677233529d2dbdb915d26ff6dda/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
# df -h /dev/shm/
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           3.9G  111M  3.8G   3% /dev/shm
```
and we can use this command to resize the /dev/shm
```
# mount -o remount,size=8G /dev/shm
```
