### ISSUE TITLE
`--pmem` pins vCPU thread at 100% CPU usage

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#2277] opened 2021-02-18 10:54 UTC
Comparing 

```target/debug/cloud-hypervisor --kernel ~/src/linux/vmlinux --pmem file=~/workloads/focal.raw --cpus boot=1 --memory size=1G --cmdline "root=/dev/pmem0p1 console=hvc0" --api-socket=/tmp/api -vv ```

with 

```target/debug/cloud-hypervisor --kernel ~/src/linux/vmlinux --disk path=~/workloads/focal.raw --cpus boot=1 --memory size=1G --cmdline "root=/dev/vda1 console=hvc0" --api-socket=/tmp/api -vv```

The `vcpu0` thread is spinning at 100% CPU usage even once booted when the io_uring block device version has settled down to ~0%

**Comment by rbradford** [comment] 2021-02-18 16:34
Using perf i've identified all the CPU usage is inside the kernel; we're not getting an spurious KVM exits and the vCPU thread is not executing in user space:

```
-    0.00%  libc-2.31.so                                                                                                                     
   - 29.76% __GI___ioctl                                                                                                                                     
      - 24.88% entry_SYSCALL_64_after_hwframe                                                                                                                
         - 24.85% do_syscall_64                                                                                                                              
            - 26.69% __x64_sys_ioctl                                                                                                                         
               - 36.90% kvm_vcpu_ioctl                                                                                                                       
                  - kvm_arch_vcpu_ioctl_run                                                                                                                  
                     - 31.17% vmx_vcpu_run                                                                                                                   
                        - 35.95% x86_virt_spec_ctrl                                                                                                          
                             native_write_msr      
```

**Comment by rbradford** [comment] 2021-02-18 16:35
@sboeuf can you try and reproduce?

**Comment by sboeuf** [comment] 2021-02-19 08:07
Just tried, and I cannot reproduce :(
I'm running Ubuntu 20.04 with 5.4.0-65-generic kernel.

**Comment by sboeuf** [comment] 2021-04-12 12:46
@rbradford do you want to keep this one open?

**Comment by rbradford** [comment] 2021-04-12 13:38
Still happens for me on F33. Let me try on Ubuntu.

**Comment by rbradford** [comment] 2021-04-12 14:21
I can reproduce this on groovy Azure as well.

**Comment by sboeuf** [comment] 2021-04-12 14:22
@rbradford oh okay that's good, well let me investigate it then :)

**Comment by sboeuf** [comment] 2021-04-12 15:14
@rbradford here is the perf report I get:
```
-   97.34%     0.00%  vcpu0            cloud-hypervisor    [.] _ZN3std3sys4unix6thread6Thread3new12thread_start17hb5e40d3d934ebb7aE                                                                                                                                 ◆
     _ZN3std3sys4unix6thread6Thread3new12thread_start17hb5e40d3d934ebb7aE                                                                                                                                                                                           ▒
     _ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17h354f9d0476051a89E                                                                                                                                                                     ▒
   - _ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17h4b0b1d1c916bfae2E                                                                                                                                                                                ▒
      - 97.32% __GI___ioctl                                                                                                                                                                                                                                         ▒
         - 75.54% entry_SYSCALL_64_after_hwframe                                                                                                                                                                                                                    ▒
            - do_syscall_64                                                                                                                                                                                                                                         ▒
               - 75.51% __x64_sys_ioctl                                                                                                                                                                                                                             ▒
                  - 75.51% ksys_ioctl                                                                                                                                                                                                                               ▒
                     - 75.51% kvm_vcpu_ioctl                                                                                                                                                                                                                        ▒
                        - kvm_arch_vcpu_ioctl_run                                                                                                                                                                                                                   ▒
                           - 75.21% vcpu_run                                                                                                                                                                                                                        ▒
                              + 66.78% vcpu_enter_guest                                                                                                                                                                                                             ▒
                                1.11% vmx_handle_exit_irqoff                                                                                                                                                                                                        ▒
                                0.93% vmx_vcpu_run                                                                                                                                                                                                                  ▒
                              + 0.70% kvm_cpu_has_pending_timer                                                                                                                                                                                                     ▒
                                0.51% vmx_prepare_switch_to_guest                                                                                                                                                                                                   ▒
           18.92% vmx_vmexit                                                                                                                                                                                                                                        ▒
           2.86% __vmx_vcpu_run
```

**Comment by sboeuf** [comment] 2021-04-12 17:10
@rbradford 
By enabling KVM tracing events, and comparing the output between the two use cases (`--disk` vs `--pmem`), I get a flood of the following in the `--pmem` case:
```
<...>-45342   [000] d... 31376.939027: kvm_entry: vcpu 0
<...>-45342   [000] d... 31376.939028: kvm_exit: vcpu 0 reason HLT rip 0xffffffff8178eadd info 0 0
```
I'm wondering why we're getting so many vm exit, but that's for sure the reason why our `vcpu` thread is entering `KVM_RUN` so many times, causing the `vcpu` thread to consume around 100%.

**Comment by sboeuf** [comment] 2021-04-12 17:30
I confirmed by running `perf stat` that we get 1,000,000 vm exits over a second with `--pmem` while we only get about 100 with `--disk`.

**Comment by sboeuf** [comment] 2021-04-15 07:45
The issue is fixed by https://github.com/cloud-hypervisor/cloud-hypervisor/pull/2498 but I don't want to close this issue since https://github.com/cloud-hypervisor/cloud-hypervisor/pull/2498 is not fixing the root cause of the problem. It's only disabling `KVM_FEATURE_ASYNC_PF_INT` while we investigate the root cause.

**Comment by sboeuf** [comment] 2021-04-22 12:40
After some time spent debugging this issue, we identified the problem was coming from KVM itself. The guest always expect to be able to initialize APF related MSRs at any point in time, but this assumption is wrong since the LAPIC might be SW disabled (SPIV register not enabled).
It works with QEMU since the FW takes care of enabling the LAPIC, but in CH case, when running direct kernel boot, there's nothing enabling the SPIV register.
KVM maintainers submitted a patch upstream for this, trying to send the APF interrupt only once the LAPIC becomes enabled. This prevent the IRQ from __not__ being injected, which then makes the CH case working fine.

The patch is the following:
```patch
KVM: x86: Properly handle APF vs disabled LAPIC situation

Async PF 'page ready' event may happen when LAPIC is (temporary) disabled.
In particular, Sebastien reports that when Linux kernel is directly booted
by Cloud Hypervisor, LAPIC is 'software disabled' when APF mechanism is
initialized. On initialization KVM tries to inject 'wakeup all' event and
puts the corresponding token to the slot. It is, however, failing to inject
an interrupt (kvm_apic_set_irq() -> __apic_accept_irq() -> !apic_enabled())
so the guest never gets notified and the whole APF mechanism gets stuck.
The same issue is likely to happen if the guest temporary disables LAPIC
and a previously unavailable page becomes available.

Do two things to resolve the issue:
- Avoid dequeuing 'page ready' events from APF queue when LAPIC is
  disabled.
- Trigger an attempt to deliver pending 'page ready' events when LAPIC
  becomes enabled (SPIV or MSR_IA32_APICBASE).

Reported-by: Sebastien Boeuf <sebastien.boeuf@intel.com>
Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>
---
 arch/x86/kvm/lapic.c | 6 ++++++
 arch/x86/kvm/x86.c   | 2 +-
 2 files changed, 7 insertions(+), 1 deletion(-)

diff --git a/arch/x86/kvm/lapic.c b/arch/x86/kvm/lapic.c
index cc369b9ad8f1..49a839d0567a 100644
--- a/arch/x86/kvm/lapic.c
+++ b/arch/x86/kvm/lapic.c
@@ -296,6 +296,10 @@ static inline void apic_set_spiv(struct kvm_lapic *apic, u32 val)
 
                 atomic_set_release(&apic->vcpu->kvm->arch.apic_map_dirty, DIRTY);
         }
+
+       /* Check if there are APF page ready requests pending */
+       if (enabled)
+               kvm_make_request(KVM_REQ_APF_READY, apic->vcpu);
 }
 
 static inline void kvm_apic_set_xapic_id(struct kvm_lapic *apic, u8 id)
@@ -2261,6 +2265,8 @@ void kvm_lapic_set_base(struct kvm_vcpu *vcpu, u64 value)
                 if (value & MSR_IA32_APICBASE_ENABLE) {
                         kvm_apic_set_xapic_id(apic, vcpu->vcpu_id);
                         static_branch_slow_dec_deferred(&apic_hw_disabled);
+                       /* Check if there are APF page ready requests pending */
+                       kvm_make_request(KVM_REQ_APF_READY, vcpu);
                 } else {
                         static_branch_inc(&apic_hw_disabled.key);
                         atomic_set_release(&apic->vcpu->kvm->arch.apic_map_dirty, DIRTY);
diff --git a/arch/x86/kvm/x86.c b/arch/x86/kvm/x86.c
index a06a6f48386d..001c6a445eaf 100644
--- a/arch/x86/kvm/x86.c
+++ b/arch/x86/kvm/x86.c
@@ -11296,7 +11296,7 @@ bool kvm_arch_can_dequeue_async_page_present(struct kvm_vcpu *vcpu)
         if (!kvm_pv_async_pf_enabled(vcpu))
                 return true;
         else
-               return apf_pageready_slot_free(vcpu);
+               return kvm_lapic_enabled(vcpu) && apf_pageready_slot_free(vcpu);
 }
 
 void kvm_arch_start_assignment(struct kvm *kvm)
-- 
2.30.2
```

Because this patch is on the host side, we can't expect having this issue solved before quite some time for most of our users.
That's why we're gonna keep the workaround disabling APF feature.

@rbradford once the patch is merged upstream, maybe we can add some code checking the KVM host version, and decide to enable APF accordingly. What do you think?

**Comment by sboeuf** [comment] 2021-04-22 13:49
Closing this issue as we agreed we'll keep the workaround disabling `KVM_FEATURE_ASYNC_PF_INT` for quite some time.

**Closed by sboeuf** 2021-04-22 13:49 UTC
