### ISSUE TITLE
Fix and reenable aarch64_acpi::test_virtio_iommu integration test

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#3941] opened 2022-04-06 07:48 UTC
This test case must be investigated and fixed before to reenable it as it's failing due to the recent introduction of error being returned when the virtio-iommu isn't able to perform the address translation it's been asked to do.

**Comment by michael2012z** [comment] 2022-04-13 05:30
Update so far:
- After a bugfix in `virtio-iommu` GVA<-> GPA translation with https://github.com/cloud-hypervisor/cloud-hypervisor/pull/3936/files , the test case for `IOMMU + ACPI` on AArch64 failed.
- The problem can be easily reproduced by appending `,iommu=on` in `--disk` parameter while booting from EDK2.
- A crash happened when EDK2 was booting. A GVA->GPA translation was called, but at the time the `virtio-iommu` device had not been initialized.
- When IOMMU is enabled, a `virtio-iommu` node is added into FDT. EDK2 parses the FDT and the address translation is invoked. This is the direct reason of the crash.
- The potential root cause could be: EDK2 failed to initialize the `virtio-iommu` device with a driver, or IOMMU shouldn't be used at the time.

@jongwu is looking more on EDK2 side.

Error log:
......
[Bds]=============End Load Options Dumping=============
[Bds]BdsWait ...Zzzzzzzzzzzz...
[Bds]BdsWait(3)..Zzzz...
.[Bds]BdsWait(2)..Zzzz...
.[Bds]BdsWait(1)..Zzzz...
..[Bds]Exit the waiting!
Process PlatformRecovery0000 (Default PlatformRecovery) ...
InstallProtocolInterface: FA920010-6785-4941-B6EC-498C579F160A FAA9CDA0
thread 'vcpu0' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "failed to translate GVA addr 0xfaa6e000" }', virtio-devices/src/transport/pci_common_config.rs:209:30

**Comment by michael2012z** [comment] 2022-04-17 03:38
I tested the same scenario (booting a guest with `virtio-iommu` from UEFI) on x86 with `rust-hypervisor-firmware` and on qemu (AArch64). The error was same in all the tests. 

Cloud Hypervisor with `rust-hypervisor-firmware` on X86:
Same error was produced:
```
# sudo target/x86_64-unknown-linux-gnu/release/cloud-hypervisor --cpus boot=1 --memory size=512M --kernel ~/workloads/hypervisor-fw --disk path=osdisk.img,iommu=on path=cloudinit --net tap=,mac=12:34:56:78:90:01,ip=192.168.1.1,mask=255.255.255.0 --serial tty --console off -vvv --log-file log.log

thread 'vcpu0' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "failed to translate GVA addr 0x13fc00" }', virtio-devices/src/transport/pci_common_config.rs:209:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'vmm' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', vmm/src/device_manager.rs:4426:35
Failed to join on VMM thread: Any { .. }
```

Qemu with `virtio-iommu-pci` on AArch64 complained the same thing and stopped:
```
# qemu-system-aarch64 -smp 4 -m 1024 -M virt -nographic -device virtio-blk-pci,drive=image -drive if=none,id=image,file=focal-server-cloudimg-arm64-custom-20210929-0-update-kernel.raw -netdev user,id=user0 -device virtio-net-device,netdev=user0 -cpu host -enable-kvm -cpu host -drive file=/usr/share/AAVMF/AAVMF_CODE.fd,if=pflash,format=raw,unit=0,readonly=on -device virtio-iommu-pci

qemu-system-aarch64: -device virtio-iommu-pci: virt-6.0 machine fails to create iommu-map device tree bindings
Check your machine implements a hotplug handler for the virtio-iommu-pci device
Check the guest is booted without FW or with -no-acpi
```

Seemingly this is an invalid test scenario. Because ACPI on AArch64 depends on UEFI. While usually `virtio-iommu` is not driven by the firmware, the GVA translation is impossible at the firmware booting stage. I think I should remove the test case `aarch64_acpi::test_virtio_iommu`.

And an immediate question is: how should `virtio-iommu` work if I have to boot from firmware? Should `virtio-iommu` be hotpluggable?

**Comment by michael2012z** [comment] 2022-04-18 03:51
> And an immediate question is: how should `virtio-iommu` work if I have to boot from firmware? Should `virtio-iommu` be hotpluggable?

There is a comment in Qemu about this:
```
Currently non DT integration is not yet supported by the kernel.
So the machine must implement a hotplug handler for the
virtio-iommu-pci device that creates the device tree iommu-map
bindings as documented in kernel documentation: Documentation/devicetree/bindings/virtio/iommu.txt
```
It seems a restriction in kernel. So `virtio-iommu` + `firmware` + `AArch64` should be impossible.

**Comment by michael2012z** [comment] 2022-04-18 06:14
Ah, there is more finding.

According to @jongwu 's test, `FW` + `virtio-iommu` on AArch64 seems possible on recent qemu. Will look into how it works.

**Comment by michael2012z** [comment] 2022-04-19 06:04
A potential solution could be: bypass the GVA translation under some carefully-selected condition in `virtio-iommu`.
The condition can be: "Not any endpoint attached". This should happen while booting from FW.

@sboeuf What's your idea?

Here is a reference of how the same problem resolved in qemu: https://github.com/qemu/qemu/commit/448179e33ea850acaf4bd3c2410acc911080e40b

**Comment by sboeuf** [comment] 2022-04-19 07:40
@michael2012z thanks for doing these investigations. I clearly understand the problem, and I think we might want to implement the `VIRTIO_IOMMU_F_BYPASS_CONFIG` feature as it would let us handle this situation (where the software doesn't have the driver to configure the `virtio-iommu`).
I don't want to introduce an extra parameter for the end user to play with the bypass feature, but we can use it internally to solve the problem.
Basically we could always start a VM with `virtio-iommu` in bypass mode, meaning if there's no driver to support it in the guest, the VM is still usable but the devices won't be seen as being behind placed behind an IOMMU. And in case there's a driver, it will disable the bypass mode through the virtio config.

Honestly I don't think we're in a hurry to implement such feature, but I've opened an issue to track it: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/3987

**Comment by michael2012z** [comment] 2022-04-19 08:11
Sure, supporting `VIRTIO_IOMMU_F_BYPASS_CONFIG` is good. With it, we can resolve this issue in a more reasonable way.

**Closed** 2022-04-26 11:07 UTC
