### ISSUE TITLE
Level triggered interrupt support

### ISSUE THREAD

**Issue by russell-islam** [cloud-hypervisor/cloud-hypervisor#3593] opened 2022-01-18 18:25 UTC
In order to support some legacy hardware that need level-triggered interrupt support, I was trying to add resample_fd to the CLH code base. But with SplitIrqCHip enabled in the Cloud Hypervisor code, it's not possible to register to resample FD. In the kernel IOCTL code, it explicitly checks if the IRQ implementation it is using is InKernel. This issue is to discuss the viability of supporting level triggered interrupt.

**Comment by sboeuf** [comment] 2022-01-18 19:38
From KVM documentation:
```
                /* KVM_EXIT_IOAPIC_EOI */
		struct {
			__u8 vector;
		} eoi;

Indicates that the VCPU's in-kernel local APIC received an EOI for a
level-triggered IOAPIC interrupt.  This exit only triggers when the
IOAPIC is implemented in userspace (i.e. KVM_CAP_SPLIT_IRQCHIP is enabled);
the userspace IOAPIC should process the EOI and retrigger the interrupt if
it is still asserted.  Vector is the LAPIC interrupt vector for which the
EOI was received.
```
And if you look here: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/vmm/src/cpu.rs#L814-L822 you'll see that what you're looking for is already implemented.

**Comment by russell-islam** [comment] 2022-01-18 20:17
That exit for x86_64 as per the code. How about aarch64?

**Comment by sboeuf** [comment] 2022-01-18 23:04
@michael2012z @MrXinWang any idea how to emulate level triggered interrupts on ARM platforms?

**Comment by michael2012z** [comment] 2022-01-19 04:59
@russell-islam For legacy devices on AArch64, we don't emulate interrupt, but simply determine the interrupt type in FDT, like: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/arch/src/aarch64/fdt.rs#L458 .  When an interrupt is triggered by a device https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/devices/src/legacy/rtc_pl031.rs#L246, the level-interrupt will be emulated by kvm.

The interrupt type of some currently supported legacy devices are like:
![image](https://user-images.githubusercontent.com/2103026/150066380-7c20ee68-ebfe-4400-9813-50abd05dee5f.png)

Is that what you asked?

**Comment by russell-islam** [comment] 2022-01-19 17:04
> @russell-islam For legacy devices on AArch64, we don't emulate interrupt, but simply determine the interrupt type in FDT, like: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/arch/src/aarch64/fdt.rs#L458 . When an interrupt is triggered by a device https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/devices/src/legacy/rtc_pl031.rs#L246, the level-interrupt will be emulated by kvm.
> 
> The interrupt type of some currently supported legacy devices are like: ![image](https://user-images.githubusercontent.com/2103026/150066380-7c20ee68-ebfe-4400-9813-50abd05dee5f.png)
> 
> Is that what you asked?

@michael2012z Does this mean that level trigger should work without any tweaking?

**Comment by michael2012z** [comment] 2022-01-20 00:59
Yes, I think so.

**Comment by russell-islam** [comment] 2022-01-25 17:21
Base on the above information looks like level triggered interrupt should work as it is right now. Will confirm once we test our hardware.

**Comment by rbradford** [comment] 2022-02-03 10:31
@russell-islam Any update?

**Comment by russell-islam** [comment] 2022-02-03 17:52
> @russell-islam Any update?

It will take time to integrate CLH into our platform.  I think it would be better if we don't track this issue with any release.
I will keep updated once we have something to share.

**Comment by sboeuf** [comment] 2022-02-04 08:27
> > @russell-islam Any update?
> 
> It will take time to integrate CLH into our platform. I think it would be better if we don't track this issue with any release. I will keep updated once we have something to share.

I think that since @michael2012z confirmed the level interrupt support is already there for aarch64, we should be able to close the issue. You can reopen it if you run into any trouble while going through the integration phase on your side.

**Closed by sboeuf** 2022-02-04 08:27 UTC

**Comment by michael2012z** [comment] 2022-05-10 03:08
@russell-islam I realized that what you asked could be something different from what I answered (about the Level triggered IRQ seen in `/proc/interrupts`).

Do you mean the legacy IRQ with `resampling`? Please see the related commits in this closed PR (https://github.com/cloud-hypervisor/cloud-hypervisor/pull/3878) if you are still interested in this.
