### ISSUE TITLE
VFIO errors/warnings

### ISSUE THREAD

**Issue by mythi** [cloud-hypervisor/cloud-hypervisor#397] opened 2019-10-29 11:05 UTC
As discussed in #379 , I'm opening another issue about the VFIO related errors/warnings I'm seeing:

```
./cloud-hypervisor/target/release/cloud-hypervisor -v --console off  --serial tty --kernel ./hypervisor-fw  --disk path=clear-31360-kvm.img --cpus 4 --memory size=1024M  --rng --net tap=,mac= --device path=/sys/bus/pci/devices/0000\:4e\:00.0/
Cloud Hypervisor Guest
        API server: /run/user/1000/cloud-hypervisor.1991
        vCPUs: 4
        Memory: 1024 MB
        Kernel: Some(KernelConfig { path: "./hypervisor-fw" })
        Kernel cmdline:
        Disk(s): Some([DiskConfig { path: "/home/mylinen/Downloads/clear-31360-kvm.img", iommu: false }])
cloud-hypervisor: 119.032153ms: ERROR:vfio/src/vfio_device.rs:438 -- Could not get region #8 info
cloud-hypervisor: 222.960728ms: WARN:vfio/src/vfio_device.rs:817 -- region write with invalid parameter, add: 4294967295, size: 4
cloud-hypervisor: 222.985829ms: WARN:vfio/src/vfio_device.rs:817 -- region write with invalid parameter, add: 4294967295, size: 4
Starting..
Page tables setup
Found PCI device vendor=8086 device=d57 in slot=0
Found PCI device vendor=1af4 device=1042 in slot=1
Found PCI device vendor=1af4 device=1041 in slot=2
Found PCI device vendor=1af4 device=1044 in slot=3
Found PCI device vendor=8086 device=37c8 in slot=4
PCI Device: 0:1.0 1af4:1042
Bar: type=MemorySpace32 address=e7f80000
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=Unused address=0

...
...
[shutdown]
[   81.583958] acpi_power_off called
cloud-hypervisor: 82.567929725s: ERROR:vfio/src/vfio_pci.rs:672 -- Could not disable MSI
cloud-hypervisor: 82.567964377s: ERROR:vfio/src/vfio_pci.rs:676 -- Could not disable MSI-X
cloud-hypervisor: 82.573047998s: ERROR:vfio/src/vfio_device.rs:355 -- Could not unset container: Os { code: 16, kind: Other, message: "Device or resource busy" }
```

**Comment by sboeuf** [comment] 2019-11-21 18:54
`Could not disable MSI` and `Could not disable MSI-X` error messages should have been fixed by #449

**Comment by sboeuf** [comment] 2020-01-22 09:37
@mythi could you give this another run with the latest cloud-hypervisor version. I expect most of these error messages to be fixed/gone.

**Comment by mythi** [comment] 2020-01-22 10:52
@sboeuf I can confirm they're gone. Thanks!

**Comment by mythi** [comment] 2020-01-22 10:57
I closed too early. With proper log levels I see:
```
$ ./cloud-hypervisor/target/release/cloud-hypervisor -v --console off  --serial tty --kernel hypervisor-fw --disk path=/home/mylinen/Downloads/clear-32060-kvm.img  --cpus boot=4 --memory size=1024M --net "tap=,mac=,ip=,mask=" --rng --device path=/sys/bus/pci/devices/0000:4f:01.0
Cloud Hypervisor Guest
        API server: /run/user/1000/cloud-hypervisor.11990
        vCPUs: 4
        Memory: 1024 MB
        Kernel: Some(KernelConfig { path: "hypervisor-fw" })
        Kernel cmdline:
        Disk(s): Some([DiskConfig { path: "/home/mylinen/Downloads/clear-32060-kvm.img", readonly: false, direct: false, iommu: false }])
cloud-hypervisor: 104.649386ms: WARN:vfio/src/vfio_device.rs:440 -- Could not get region #8 info
cloud-hypervisor: 208.489012ms: WARN:vfio/src/vfio_device.rs:818 -- region write with invalid parameter, add: 4294967295, size: 4
cloud-hypervisor: 208.535164ms: WARN:vfio/src/vfio_device.rs:818 -- region write with invalid parameter, add: 4294967295, size: 4
L
Starting..
```

the errors upon shutdown are gone.

**Comment by sboeuf** [comment] 2020-01-22 11:09
Thanks @mythi 
Here's a summary:
- `WARN:vfio/src/vfio_device.rs:440 -- Could not get region #8 info` is expected, that's why it does not appear as an ERROR, just a WARN.
- `WARN:vfio/src/vfio_device.rs:818 -- region write with invalid parameter, add: 4294967295, size: 4` needs some further investigation.
- `WARN:vmm/src/memory_manager.rs:152 -- Unexpected offset for accessing memory manager device: 12` should be fixed once we merge #644

**Comment by sboeuf** [comment] 2020-01-22 13:59
@mythi about the issue that needs further investigation, I cannot reproduce it with the device I have. Could you run the following test for me:
- Apply the following patch
```diff
diff --git a/vfio/src/vfio_device.rs b/vfio/src/vfio_device.rs
index 9c40c51..c46ac91 100644
--- a/vfio/src/vfio_device.rs
+++ b/vfio/src/vfio_device.rs
@@ -811,13 +811,22 @@ impl VfioDevice {
         }

         let size = buf.len() as u64;
-        if size > stub.size
-            || addr + size > stub.size
-            || (stub.flags & VFIO_REGION_INFO_FLAG_WRITE) == 0
-        {
+        if size > stub.size {
             warn!(
-                "region write with invalid parameter, add: {}, size: {}",
-                addr, size
+                "###1 region write with invalid parameter, addr: {}, size: {}, stub.size {}",
+                addr, size, stub.size
+            );
+            return;
+        } else if addr + size > stub.size {
+            warn!(
+                "###2 region write with invalid parameter, addr: {}, size: {}, stub.size {}",
+                addr, size, stub.size
+            );
+            return;
+        } else if (stub.flags & VFIO_REGION_INFO_FLAG_WRITE) == 0 {
+            warn!(
+                "###3 region write with invalid parameter, addr: {}, size: {}, stub.flags {}",
+                addr, size, stub.flags
             );
             return;
         }
```
- Run the VM again and post the result. It'll help narrow down the problem.

**Comment by mythi** [comment] 2020-01-22 14:58
```
$ ./cloud-hypervisor/target/release/cloud-hypervisor -v --console off  --serial tty --kernel hypervisor-fw --disk path=/home/mylinen/Downloads/clear-32060-kvm.img  --cpus boot=4 --memory size=1024M --net "tap=,mac=,ip=,mask=" --rng --device path=/sys/bus/pci/devices/0000:4f:01.0
Cloud Hypervisor Guest
        API server: /run/user/1000/cloud-hypervisor.12484
        vCPUs: 4
        Memory: 1024 MB
        Kernel: Some(KernelConfig { path: "hypervisor-fw" })
        Kernel cmdline:
        Disk(s): Some([DiskConfig { path: "/home/mylinen/Downloads/clear-32060-kvm.img", readonly: false, direct: false, iommu: false }])
cloud-hypervisor: 111.464261ms: WARN:vfio/src/vfio_device.rs:440 -- Could not get region #8 info
cloud-hypervisor: 215.378102ms: WARN:vfio/src/vfio_device.rs:821 -- ###2 region write with invalid parameter, addr: 4294967295, size: 4, stub.size 4096
cloud-hypervisor: 215.449672ms: WARN:vfio/src/vfio_device.rs:821 -- ###2 region write with invalid parameter, addr: 4294967295, size: 4, stub.size 4096
L
Starting..
Setting up 4 GiB identity mapping
Page tables setup
Found PCI device vendor=8086 device=d57 in slot=0
Found PCI device vendor=1af4 device=1042 in slot=1
Found PCI device vendor=1af4 device=1041 in slot=2
Found PCI device vendor=1af4 device=1044 in slot=3
Found PCI device vendor=8086 device=37c9 in slot=4
PCI Device: 0:1.0 1af4:1042
Bar: type=MemorySpace32 address=e7f80000
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=Unused address=0
Virtio block device configured. Capacity: 17909679 sectors
Found EFI partition
Filesystem ready
Jumping to kernel
cloud-hypervisor: 1.098875049s: WARN:vmm/src/memory_manager.rs:152 -- Unexpected offset for accessing memory manager device: 12
cloud-hypervisor: 1.099011862s: WARN:vmm/src/memory_manager.rs:152 -- Unexpected offset for accessing memory manager device: 12
cloud-hypervisor: 1.09912883s: WARN:vmm/src/memory_manager.rs:152 -- Unexpected offset for accessing memory manager device: 12
cloud-hypervisor: 1.099255362s: WARN:vmm/src/memory_manager.rs:152 -- Unexpected offset for accessing memory manager device: 12
cloud-hypervisor: 1.099376749s: WARN:vmm/src/memory_manager.rs:152 -- Unexpected offset for accessing memory manager device: 12
cloud-hypervisor: 1.099501889s: WARN:vmm/src/memory_manager.rs:152 -- Unexpected offset for accessing memory manager device: 12
cloud-hypervisor: 1.099623036s: WARN:vmm/src/memory_manager.rs:152 -- Unexpected offset for accessing memory manager device: 12
cloud-hypervisor: 1.099743873s: WARN:vmm/src/memory_manager.rs:152 -- Unexpected offset for accessing memory manager device: 12
```

**Comment by sboeuf** [comment] 2020-01-22 15:15
Thanks @mythi!
I think it's obvious there's a mistake with the check `else if addr + size > stub.size`, which should be `else if addr + size > stub.offset + stub.size`. Let me fix that :)

**Comment by sboeuf** [comment] 2020-01-22 16:22
Yes I confirm the `addr` should not be as big as `0xFFFFFFFF`. The address is the offset in the region, there's no reason to have such huge offset.
It'd be easier if I could have access to your machine to do some further debugging.

**Comment by sboeuf** [comment] 2020-01-23 12:12
@mythi ok so now that both #653 (fixing `WARN:vfio/src/vfio_device.rs:818 -- region write with invalid parameter, add: 4294967295, size: 4`) and #644 (fixing `WARN:vmm/src/memory_manager.rs:152 -- Unexpected offset for accessing memory manager device: 12`) have been merged, the only warning message left should be `WARN:vfio/src/vfio_device.rs:440 -- Could not get region #8 info` (which is expected).
I think you can close this issue after doing a last check :)

**Comment by mythi** [comment] 2020-01-23 12:36
@sboeuf yes, I can confirm!

```
 $ ./cloud-hypervisor/target/release/cloud-hypervisor -v --console off  --serial tty --kernel hypervisor-fw --disk path=/home/mylinen/Downloads/clear-32060-kvm.img  --cpus boot=4 --memory size=1024M --net "tap=,mac=,ip=,mask=" --rng --device path=/sys/bus/pci/devices/0000:4f:01.0
Cloud Hypervisor Guest
        API server: /run/user/1000/cloud-hypervisor.15157
        vCPUs: 4
        Memory: 1024 MB
        Kernel: Some(KernelConfig { path: "hypervisor-fw" })
        Kernel cmdline:
        Disk(s): Some([DiskConfig { path: "/home/mylinen/Downloads/clear-32060-kvm.img", readonly: false, direct: false, iommu: false }])
cloud-hypervisor: 110.095253ms: WARN:vfio/src/vfio_device.rs:440 -- Could not get region #8 info
L
Starting..
Setting up 4 GiB identity mapping
Page tables setup
Found PCI device vendor=8086 device=d57 in slot=0
Found PCI device vendor=1af4 device=1042 in slot=1
Found PCI device vendor=1af4 device=1041 in slot=2
Found PCI device vendor=1af4 device=1044 in slot=3
Found PCI device vendor=8086 device=37c9 in slot=4
PCI Device: 0:1.0 1af4:1042
Bar: type=MemorySpace32 address=e7f80000
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=MemorySpace32 address=0
Bar: type=Unused address=0
Virtio block device configured. Capacity: 17909679 sectors
Found EFI partition
Filesystem ready
Jumping to kernel
...
```

**Closed** 2020-01-23 12:36 UTC
