### ISSUE TITLE
test_vfio failing after Azure VM upgrade

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#4324] opened 2022-07-16 07:30 UTC
```
[   32.823268] bash[1423]: cloud-hypervisor: 124.188929ms: <vcpu0> ERROR:vmm/src/cpu.rs:1040 -- VCPU generated error: VcpuRun(Failed to run vcpu: Unexpected exit reason on vcpu run: FailEntry(7, 3)
[   32.823336] bash[1423]: Caused by:
[   32.823401] bash[1423]:     Unexpected exit reason on vcpu run: FailEntry(7, 3))
```

I think this is the same error that prevented us from moving to jammy: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/4131

**Comment by rbradford** [comment] 2022-07-16 07:36
Looks like the 20.04 Azure LTS kernel was updated from 5.13 to 5.15 (the `prepare_vdpa.sh` script builds a module so we can see the version difference across two builds.)

**Comment by liuw** [comment] 2022-07-16 09:33
> Looks like the 20.04 Azure LTS kernel was updated from 5.13 to 5.15 (the `prepare_vdpa.sh` script builds a module so we can see the version difference across two builds.)

I think this may be a known issue -- the one you discovered some time ago.

We've got a patch, but it is not very suitable for upstream. :-(

**Comment by sboeuf** [comment] 2022-07-18 08:32
@rbradford what can we do about this in the short term? Seems like we're gonna have to disable `test_vfio` for a while :-/
Maybe we can rely on our baremetal CI, or rely on an other CSP for running this test?

**Comment by liuw** [comment] 2022-07-18 09:07
> @rbradford what can we do about this in the short term? Seems like we're gonna have to disable `test_vfio` for a while :-/ Maybe we can rely on our baremetal CI, or rely on an other CSP for running this test?

Not sure if switching to another cloud can fair better because it is 5.15 KVM that's broken. Even if it works on KVM it works by chance.

We can perhaps pin the kernel version by using `apt-mark`.

```apt-mark hold $KERNEL_PKG $KERNEL_HEADER_PKG```

It is also surprising Ubuntu chose to do such a major bump in their LTS kernel.

**Comment by rbradford** [comment] 2022-07-19 11:30
> > @rbradford what can we do about this in the short term? Seems like we're gonna have to disable `test_vfio` for a while :-/ Maybe we can rely on our baremetal CI, or rely on an other CSP for running this test?
> 
> Not sure if switching to another cloud can fair better because it is 5.15 nested KVM that's broken. Even if it works on KVM it works by chance. Bare metal CI should work.
> 
> We can perhaps pin the kernel version by using `apt-mark`.
> 
> `apt-mark hold $KERNEL_PKG $KERNEL_HEADER_PKG`
> 

Unfortunately we create a new VM for the tests and to downgrade the kernel would then require a reboot which I don't think would work well with Jenkins SSHing in to run the commands. We could build a custom image and use that but that is something we have had issues with in the past and it's tedious to keep up to date for security compliance.

> It is also surprising Ubuntu chose to do such a major bump in their LTS kernel.

Yeh, it seems it is only the Azure kernel that is bumped (`linux-generic` is still 5.4)

**Comment by liuw** [comment] 2022-07-19 15:37
Then perhaps the best solution right now is to move the vfio tests to bare metal and wait for the regression to be fixed and propagated to Ubuntu.

**Comment by sboeuf** [comment] 2022-07-20 08:00
Yes seems like it, but this is going to take quite some time given the fix isn't even submitted upstream :-/

**Comment by liuw** [comment] 2022-07-20 08:08
> Yes seems like it, but this is going to take quite some time given the fix isn't even submitted upstream :-/

Our (simple) fix was submitted, but a proper fix is being worked on by Red Hat. The proper fix (a dozen patches) is not going to land any time soon.

**Comment by sboeuf** [comment] 2022-07-20 08:22
Thanks for the update on this.

**Comment by rbradford** [comment] 2022-07-21 07:50
> Then perhaps the best solution right now is to move the vfio tests to bare metal and wait for the regression to be fixed and propagated to Ubuntu.

Yeh, we already have very comprehensive VFIO testing that happens on the master branch.

**Comment by rbradford** [comment] 2022-09-22 09:00
@liuw Any update on this?

**Comment by liuw** [comment] 2022-09-22 20:09
I think the patch series is still pending.

**Comment by likebreath** [comment] 2023-06-20 19:16
@liuw Any updates regarding this issue? It would be good if we can move the common "test_vfio" test back to Azure VM worker for running on each PR.

**Comment by liuw** [comment] 2023-06-20 23:58
@likebreath there were quite a few fixes to the host hypervisor in the past year. Can you just reenable this test case?

**Comment by liuw** [comment] 2023-06-20 23:59
@likebreath I saw the update in the other PRs. You've already tried and it failed the same way?

**Comment by likebreath** [comment] 2023-06-21 22:08
> there were quite a few fixes to the host hypervisor in the past year. Can you just reenable this test case?

@liuw This is good to know. We can't reenable this `test_vfio` test now as it is stilling failing (due to a different error) [1].

> I saw the update in the other PRs. You've already tried and it failed the same way?

No, I haven't tried the `test_vfio` test on Azure VMs recently.  The failure I mentioned in other PRs recently is the same one I mentioned above [1].

[1] https://github.com/cloud-hypervisor/cloud-hypervisor/issues/5190#issuecomment-1599357074

**Comment by rmstoi** [comment] 2023-08-30 10:46
@likebreath @liuw  #5190 has been closed, any chance same fix closed this issue too?
If not how does this issue differ?

**Comment by rbradford** [comment] 2023-08-30 14:42
Simply open a PR that tries `test_vfio` on an on-demand worker.

**Comment by likebreath** [comment] 2023-08-30 23:31
Opened a PR #5717 to try the test on the latest Azure VMs, and looks like the test is still failing for the same reason:
```
[2023-08-30T21:14:46.959Z] [   31.134641] bash[1702]: cloud-hypervisor: 217.153754ms: <vcpu0> ERROR:vmm/src/cpu.rs:1069 -- VCPU generated error: VcpuRun(Failed to run vcpu: Unexpected exit reason on vcpu run: FailEntry(7, 2)
[2023-08-30T21:14:46.959Z] [   31.134949] bash[1702]: Caused by:
[2023-08-30T21:14:46.959Z] [   31.135516] bash[1702]:     Unexpected exit reason on vcpu run: FailEntry(7, 2))
```

**Comment by jepio** [comment] 2023-09-07 16:59
I'd like to take a look - I've gotten a similar VFIO test case to work for Kata (Azure->KVM(+Qemu)->KVM(+CLH)).

**Comment by rbradford** [comment] 2023-09-09 07:00
@likebreath Kernel got bumped in the last few days (see #5757) so it might be worth testing again.

**Closed** 2023-09-15 07:07 UTC
Labels: CI
