### ISSUE TITLE
The VMM shutdown endpoint does not work on paused VMs

### ISSUE THREAD

**Issue by sameo** [cloud-hypervisor/cloud-hypervisor#816] opened 2020-02-24 13:21 UTC
When calling `/vmm/shutdown` on a paused VM, we never get a reply.

**Comment by russell-islam** [comment] 2020-04-27 19:44
I believe this issue is fixed by #1084

**Comment by russell-islam** [comment] 2020-04-27 19:47
I believe  this issue is fixed by https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1064

**Comment by likebreath** [comment] 2020-04-27 22:09
@russell-islam I think you are right. Closing it.

**Comment by russell-islam** [comment] 2020-04-27 22:13
@likebreath thank you.

**Comment by rbradford** [comment] 2020-04-28 10:26
I don't think it is perfectly resolved. I just tested it. Sometimes it still blocks and the threads aren't cleaned up.

**Comment by sameo** [comment] 2020-04-28 10:46
@rbradford Are you able to reproduce it with a specific config? Or is it just random?

**Comment by rbradford** [comment] 2020-04-28 12:27
> @rbradford Are you able to reproduce it with a specific config? Or is it just random?

Not an especially fancy configuration:

`target/debug/cloud-hypervisor --kernel ~/src/rust-hypervisor-firmware/target/target/release/hypervisor-fw --disk path=/home/rob/workloads/clear-32360-kvm.img --console off --serial tty --cpus boot=4 --memory size=1024M --rng --api-socket=/tmp/api`

Sadly it doesn't reproduce significantly so I believe there is still a race.

**Comment by likebreath** [comment] 2020-04-29 05:09
@rbradford Thanks for double checking on this. I should have ran the tests before I closed the issue. Sorry about that.

This issue can still be easily reproduced (~90%) on my side . I was using the simple config from our README.md. Also, the VMM was hanging and not responding to any HTTP APIs, so #817 seems not be resolved either. I will take a closer look tomorrow.

**Comment by russell-islam** [comment] 2020-04-29 17:06
I will investigate more on these as well.

**Comment by russell-islam** [comment] 2020-04-29 20:41
@likebreath I was trying to reproduce the issue but not able to do it. I am using following command from one terminal.

./cloud-hypervisor/target/release/cloud-hypervisor --kernel hypervisor-fw --disk path=clear-31890-kvm.img --cmdline "console=hvc0 reboot=k panic=1 nomodules i8042.noaux i8042.nomux i8042.nopnp i8042.dumbkbd root=/dev/vda3" --cpus boot=4 --memory size=1024M --net "tap=,mac=,ip=,mask=" --rng --api-socket /tmp/cloud-hypervisor.sock -vv --log-file /tmp/dbg.log

From another terminal I am running following script to reproduce the issue:

```#!/bin/bash
for (( c=0; c<100; c++ ))
do
        echo "Test # $c"
        echo "sleeping 4 seconds"
        sleep 4
        echo "Pausing the VM"
        curl --unix-socket /tmp/cloud-hypervisor.sock -i -X PUT 'http://localhost/api/v1/vm.pause'

        sleep 1
        echo "Shutting doen the VM"
        curl --unix-socket /tmp/cloud-hypervisor.sock -i -X PUT 'http://localhost/api/v1/vm.shutdown'

        sleep 1
        echo "Booting the VM"
        curl --unix-socket /tmp/cloud-hypervisor.sock -i -X PUT 'http://localhost/api/v1/vm.boot'
done

echo "test done $c times"
```

Could please share your steps to reproduce this issue?

**Comment by likebreath** [comment] 2020-04-29 22:33
@russell-islam That's strange.  I tried almost the same command as yours (see blow), and was able to get the hang reproduced quickly... I don't have to ran it in a loop, as I normally get a hang by calling `vmm/shutdown` (or `vm.shutdown`) after the VM is up and a call to `vm/pause`.

Here is the details of my setup for your reference:

CLI command:
```
/home/chenb/project/cloud-hypervisor/cloud-hypervisor/target/release/cloud-hypervisor \                                                                                                                   
    --kernel /home/chenb/project/cloud-hypervisor/rust-hypervisor-firmware/target/target/release/hypervisor-fw \                                                                                          
    --disk path=/home/chenb/project/cloud-hypervisor/linux-cloud-hypervisor/clear-31890-kvm.img \                                                                                                         
    --cmdline "console=hvc0 reboot=k panic=1 nomodules i8042.noaux i8042.nomux i8042.nopnp i8042.dumbkbd root=/dev/vda3" \                                                                                
    --cpus boot=4 --memory size=1024M  --net "tap=,mac=,ip=,mask=" --rng --api-socket /tmp/api -vv --log-file /tmp/dbg.log 
```

My cloud-hypervisor version is [master upstream](https://github.com/cloud-hypervisor/cloud-hypervisor/commit/2f0bc06becfc6e3a4f1414e5874528c752cdd2e2):
```
/home/chenb/project/cloud-hypervisor/cloud-hypervisor/target/release/cloud-hypervisor --version
cloud-hypervisor v0.6.0-347-g2f0bc06b
```

The rust-fw is also [master upstream](https://github.com/cloud-hypervisor/rust-hypervisor-firmware/commit/871f6b1d6c0550d6e73cd5da089660a00af6ac22).

**Comment by russell-islam** [comment] 2020-04-30 00:14
Yeah, this is strange. I am using root user: Memory:64GB CPU: 12

**Comment by likebreath** [comment] 2020-05-06 01:48
@russell-islam Here is some update from my side. I think the root cause of the hanging is that the `vcpu` thread sometimes blocks on `KVM_RUN ioctls` and does not terminate (on paused VMs). Few observations that suggest this conclusion: 1) gbd back-trace; 2) the `vcpu` thread is not waiting for any other threads and is the first one to terminate on normal (non-hanging) situations; 3) killing `vcpu` thread manually w/ `kill -34` (`SIGRTMIN`) stops the hanging and makes CH process terminate gracefully.

The  blocking `KVM_RUN ioctls` from the `vcpu` thread is supposed to be interrupted by the `vmm` thread through function `VcpuState::singal_thread()` [here](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/vmm/src/cpu.rs#L949-L955). The `VcpuState::singal_thread()` function looks fine to me and works as expected from my debugging ( e.g. `libc::pthread_kill()` returns `0` and the vcpu thread `handle` is always active and correct).  The problem seems to be on the signal handler side (from the `vcpu` thread). Surprisingly, the signal handler is [empty](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/vmm/src/cpu.rs#L837) and is registered [here](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/vmm/src/cpu.rs#L837-L839) (while creating new `vcpu` threads). 

What I don't understand is how is this empty handler guaranteed to interrupt `KVM_RUN ioctls`? From a quick glance of qemu's code, they are using either [`KVM_CAP_IMMEDIATE_EXIT`](https://github.com/qemu/qemu/blob/master/accel/kvm/kvm-all.c#L1925) or [`KVM_SET_SIGNAL_MASK`](https://github.com/qemu/qemu/blob/master/accel/kvm/kvm-all.c#L2824) to interrupt/kick-out the `vcpu` thread. I am not sure if we need do similar things.

@rbradford @sboeuf I will need your help to understand more about it.

**Comment by sboeuf** [comment] 2020-05-06 08:37
I think the semantic used to handle `pause()` and `shutdown()` is wrong because it assumes the thread is running (`KVM_RUN`) at all time, and it assumes that issuing a `SIGRTMIN` signal will get the KVM_RUN to exit.
Problem is, the thread itself might not be running `KVM_RUN`, but instead it might be in the code checking for a kill signal or a pause signal.
@sameo @rbradford I don't know what's your opinion on how to solve this, but I would suggest that for the kill, we should simply issue a `SIGTERM` to each vCPU thread, as we are sure the thread itself will get killed (where the `SIGRTMIN` was simply a way to make KVM_RUN exit).
If we go with this approach for `kill`, then we need another approach for `pause` too.

**Comment by rbradford** [comment] 2020-05-06 09:10
You have to use a real time signal (e.g. `SIGRTMIN`) to target an individual thread. Sending `SIGRTMIN` will make the `ioctl()` exit with -EINTR`.

I think rather than attempting to transition from the `PAUSED` state and then semantically allow the vCPU to run. We should instead modify the `Vcpu::shutdown()` to handle the paused case. Let me create a PR and see if that resolves the issue.

**Comment by sboeuf** [comment] 2020-05-06 09:14
Ok so if you apply this patch (obviously not a patch), you will be able to reproduce this issue consistently.
```diff
diff --git a/vmm/src/cpu.rs b/vmm/src/cpu.rs
index 05047a37..7a3858a4 100644
--- a/vmm/src/cpu.rs
+++ b/vmm/src/cpu.rs
@@ -872,6 +872,7 @@ impl CpuManager {
                         // pause boolean has been toggled.
                         while vcpu_pause_signalled.load(Ordering::SeqCst) {
                             thread::park();
+                            thread::sleep_ms(1000);
                         }
                     }
                 })
```

Now I think there's a simple way to solve the problem I explained in my earlier comment, which will not involve any redesign. The point is to validate that we're not expecting the thread to be `killed` or `paused` right before it enters a new `KVM_RUN`.
So here is the patch I think should solve all potential issues related to the race condition explained earlier:
```diff
diff --git a/vmm/src/cpu.rs b/vmm/src/cpu.rs
index 05047a37..081d7925 100644
--- a/vmm/src/cpu.rs
+++ b/vmm/src/cpu.rs
@@ -844,15 +844,20 @@ impl CpuManager {
 
                     loop {
                         // vcpu.run() returns false on a KVM_EXIT_SHUTDOWN (triple-fault) so trigger a reset
-                        match vcpu.lock().unwrap().run() {
-                            Err(e) => {
-                                error!("VCPU generated error: {:?}", e);
-                                break;
-                            }
-                            Ok(true) => {}
-                            Ok(false) => {
-                                reset_evt.write(1).unwrap();
-                                break;
+                        if !vcpu_kill_signalled.load(Ordering::SeqCst)
+                            && !vcpu_kill.load(Ordering::SeqCst)
+                            && !vcpu_pause_signalled.load(Ordering::SeqCst)
+                        {
+                            match vcpu.lock().unwrap().run() {
+                                Err(e) => {
+                                    error!("VCPU generated error: {:?}", e);
+                                    break;
+                                }
+                                Ok(true) => {}
+                                Ok(false) => {
+                                    reset_evt.write(1).unwrap();
+                                    break;
+                                }
                             }
                         }
```

**Comment by rbradford** [comment] 2020-05-06 09:38
@sboeuf right, something like that (I did it differently) you can see in my PR. There are other bits you need to do too.

**Comment by rbradford** [comment] 2020-05-06 09:42
What we really want to do is make sure kill is set before unsetting pause. And to do that we can't use the existing `Vm::resume()` as the vCPU could run before it gets to the `Vcpu::shutdown()`. The solution is to make `Vcpu:shutdown()` set kill and clear pause. We also have to handle the `DeviceManager` threads but that is okay as we can do it with `DeviceManager::resume()`

**Closed** 2020-05-07 07:00 UTC
