### ISSUE TITLE
Writes to SerialBuffer lost

### ISSUE THREAD

**Issue by bryteise** [cloud-hypervisor/cloud-hypervisor#3170] opened 2021-09-27 18:23 UTC
When a `SerialBuffer` attempts to write to a PTY fd that does not have a client connected the write does not block and the bytes are lost until a limit (20480 bytes on my system) and then the writes will block and are added to the `SerialBuffer`'s circular buffer. If a client connects to the PTY and the circular buffer is cleared and the client then disconnects the behavior of lost writes will repeat.

**Comment by rbradford** [comment] 2021-11-02 11:08
@bryteise Do you have a way to reproduce this?

**Comment by rbradford** [comment] 2021-11-16 12:18
Looks like using `EPOLLOUT` + whether the write blocks isn't a good indicator as to whether there is anything on the other side. Perhaps this approach would work: https://stackoverflow.com/questions/3486491/how-can-i-detect-when-someone-opens-the-slave-side-of-a-pty-pseudo-terminal-in

**Comment by sboeuf** [comment] 2022-08-16 15:56
Do we want to take any action on this? If not, let's close it.

**Comment by rbradford** [comment] 2022-08-16 16:00
This is a real, reproducible bug, sadly.

**Comment by sboeuf** [comment] 2022-08-16 16:08
Can we describe an action plan/design for anyone with some time to pick up this issue?

**Comment by rbradford** [comment] 2022-08-16 16:11
@sboeuf This would be a really good way to learn some interesting kernel internals / Linux semantics. It's pretty straightforward to reproduce following the instructions in the description of the issue.

**Comment by sboeuf** [comment] 2022-08-16 16:18
Alright I'll have a look at it when I have some spare time :)

**Comment by sboeuf** [comment] 2022-08-19 09:48
A quick update:
- The PR #4520 fixes the issue described here.
- The same problem exists on `virtio-console` but it will require a dedicated patch since the implementation is much different with the handling being done through the `virtio-console` thread directly. (#4521)
- I've identified the PTY resize isn't working with `virtio-console` (`serial` can't support it anyway), this must be fixed. (#4522)

**Closed** 2022-08-19 13:39 UTC
