### ISSUE TITLE
Windows generates some IOAPIC error messages

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#1791] opened 2020-10-01 13:06 UTC
```
cloud-hypervisor: 2.879159183s: ERROR:devices/src/ioapic.rs:238 -- IOAPIC: invalid write to register offset
cloud-hypervisor: 2.879262017s: ERROR:devices/src/ioapic.rs:238 -- IOAPIC: invalid write to register offset
```

**Comment by sboeuf** [comment] 2020-10-05 08:25
I've updated the error log in the code, and here is what I get:
```
cloud-hypervisor: 1.858660908s: ERROR:devices/src/ioapic.rs:238 -- IOAPIC: invalid write to register offset 0x1
```
Problem is, the offset 0x1 refers to the IOAPICVER register, which is read only. So either Windows is doing something wrong, or the IOAPIC specification I have is incomplete, or partially wrong.

**Comment by rbradford** [comment] 2020-10-05 13:40
I saw this was out-of-spec too. I opened this issue for @weltling or @liuw to check the source code for this.

**Comment by liuw** [comment] 2020-10-05 15:18
Windows writes 0 to the version register and read from it, do this twice in a row to determine if the IO-APIC is valid. It thinks it is the "documented detection mechanism", but I couldn't find any reference.

I think this issue is mostly benign. Of course to close this we should make sure it is really writing 0 here so that we know it is the same behaviour I described.

**Comment by weltling** [comment] 2020-10-05 15:31
Found same as @liuw, also about the "documented" comment :) This seems indeed harmless except it will will think the I/O unit is not available. One could try to let in read/write zeroes. The spec however tells that the version register is read only.

Thanks.

**Comment by sboeuf** [comment] 2020-10-05 16:22
@liuw I can confirm I can see Windows writing 0 twice. So I think the behavior you're describing is exactly what's happening. I agree it's totally benign, but I don't want to modify the IOAPIC implementation unless there's specification saying it's okay to write to the IOAPICVER register.

**Comment by liuw** [comment] 2020-10-05 16:29
Thanks for confirming.

There is no need to modify CH's IO-APIC code. Windows should function just fine because two reads return the same result.

If people care, we can reference this issue in the log message; otherwise I think this issue can be closed.

**Comment by sboeuf** [comment] 2020-10-06 07:02
Sounds good @liuw 

@rbradford please close the issue if this is okay with you.

**Comment by rbradford** [comment] 2020-10-06 09:04
I think we should modify the ioapic implementation to accept this behaviour (maybe cross reference with Linux) so that we do not give warnings to the user.

**Closed** 2020-10-06 17:13 UTC
