### ISSUE TITLE
Random systemd crash hangs guest boot when launching with SPDK/NVMe as a VFIO user device

### ISSUE THREAD

**Issue by likebreath** [cloud-hypervisor/cloud-hypervisor#3352] opened 2021-11-18 15:11 UTC
When launching a Cloud Hypervisor guest with SPDK/NVMe as a VFIO user device, we observed that the systemd daemon sometimes core dump and prevent the guest from booting.  The error message (from the guest kernel) reports either ABRT or SEGV. It looks like a memory corruption issue to the guest memory, but we are not sure who (the vfio-user client code in Cloud Hypervisor, the vfio-user server code from SPDK/NVMe, or the vfio-user protocol itself) causes the issue.

**Comment by likebreath** [comment] 2021-11-18 15:40
Here is my setup to reproduce the error:

* Upstream Cloud Hypervisor: https://github.com/cloud-hypervisor/cloud-hypervisor/tree/58d984f6b8bdb5fd05e8ba1a2c12124797cb7b4c
* NVMf/vfio-user in SPDK: https://github.com/spdk/spdk/commit/0814f8662a5f18d5bdabfcb2d299b0bc9f40e726 (upstream)
* NVMf/vfio-user was setup based on the [vfio-user.md](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/vfio-user.md#example-nvme-device)
* The guest kernel: custom build v5.14 from https://github.com/cloud-hypervisor/linux/tree/ch-5.14 (same as the one used by our CI)
* The guest image: focal-server-cloudimg-amd64-custom-20210609-0.raw (same as the cone used by our CI)


Cloud Hypervisor command based on [vfio-user.md](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/vfio-user.md#example-nvme-device):
```
cloud-hypervisor/target/release/cloud-hypervisor \
    --cpus boot=4 \
    --api-socket /tmp/clh.sock \
    --memory size=1G,shared=on \
    --log-file /tmp/clh.log \
    --kernel ~/workloads/vmlinux \
    --cmdline "root=/dev/vda1 console=hvc0" \
    --user-device socket=/tmp/test-vfio-user/nvme-vfio-user/cntrl \
    --disk path=./focal-server-cloudimg-amd64-custom-20210609-0.raw
```

Qemu also encountered the same error using the same setup. Here is a sample Qemu command based on the [gpio example from libvfio-user](https://github.com/nutanix/libvfio-user#gpio):
```
oracle-qemu/build/qemu-system-x86_64 \
    -mem-prealloc -m 256 \
    -object memory-backend-file,id=ram-node0,prealloc=yes,mem-path=/dev/hugepages/nvme,share=yes,size=256M \
    -numa node,memdev=ram-node0 \
    -enable-kvm \
    -kernel ~/workloads/vmlinux \
    -nographic \
    -append "console=ttyS0 root=/dev/vda1" \
    -device virtio-blk-pci,drive=image -drive if=none,id=image,file=./focal-server-cloudimg-amd64-custom-20210609-0.raw,format=raw \
    -device vfio-user-pci,socket=/tmp/test-vfio-user/nvme-vfio-user/cntrl
```
Note: The qemu is built from https://github.com/oracle/qemu/tree/vfio-user-v0.93 [1], and the libvfio-user submodule from SPDK needs to be update manually to its upstream (https://github.com/nutanix/libvfio-user/tree/ace83abb5d62ef91bafd20219be1bdaf4f57f091) [2].

[1] https://github.com/nutanix/libvfio-user/issues/625#issuecomment-970091483
[2] https://github.com/nutanix/libvfio-user/issues/625#issuecomment-970092996

**Comment by likebreath** [comment] 2021-11-18 15:53
With the help from vfio-user maintainers (@tmakatos @jlevon @swapnili) and additional experiments, I found that the custom guest kernel we are using make a difference, e.g., the issue does not happen any more when we switch to use the stock kernel from the guest image. For example, launching Cloud Hypervisor in the following way is working perfectly fine:
```
cloud-hypervisor/target/release/cloud-hypervisor \
    --cpus boot=4 \
    --api-socket /tmp/clh.sock \
    --memory size=1G,shared=on \
    --log-file /tmp/clh.log \
    --kernel ~/workloads/hypervisor-fw \
    --console off --serial tty \
    --user-device socket=/tmp/test-vfio-user/nvme-vfio-user/cntrl \
    --disk path=./focal-server-cloudimg-amd64-custom-20210609-0.raw
```
To dig into the issue more, I am looking at two fronts: 1. make sure the NVMe backend is writing to the correct range of guest memory (through instrumenting both the NVMe backend and the nvme driver); 2. try to get a core dump from the crashed systemd.

Any questions or advises, please don't hesitate to share. Thank you.

**Comment by rbradford** [comment] 2021-11-18 17:33
Can you try using hypervisor-fw and put our reference kernel inside the image so then you can identify if it's a different booting method which is what is helpful vs anything to do with the kernel version.

**Comment by rbradford** [comment] 2021-11-18 18:16
@likebreath You could also try direct kernel booting with those known good kernel images (hard as they probably use initramfs) or direct boot a kernel built from a tag for a known good kernel version.

One thing to note is that hypervisor-fw starts the kernel with the bottom 4GiB already mapped with 2MiB huge pages (via CR4 PAE). I don't think that's the case for the Linux kernel directly loaded by PVH.

**Comment by sboeuf** [comment] 2021-11-24 08:37
@likebreath found the root cause was the lack of `CONFIG_NVME_MULTIPATH` in the guest kernel configuration, which makes total sense given the issue we were getting.
@likebreath feel free to close the issue!

**Comment by rbradford** [comment] 2021-11-28 17:42
Why does systemd crash when that config option is missing? Did you find/open an issue with systemd about that?

**Comment by tmakatos** [comment] 2021-11-29 10:02
@likebreath, @jlevon ran into a similar issue but he was using 128 namespaces. How many namespaces are you using?

**Comment by jlevon** [comment] 2021-11-29 10:24
Some more details would be interesting. The issue I had was with combinatorial explosion of queues in the multipath daemon code that would cause timeouts

**Comment by likebreath** [comment] 2021-11-29 21:15
> Why does systemd crash when that config option is missing? 

I am not sure about that. The solution of adding `CONFIG_NVME_MULTIPATH` kernel config came from comparing our [custom kernel config](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/resources/linux-config-x86_64) and the kernel config for the stock kernel of Ubuntu 20.10 (v5.13). Along the debugging process, I located the hanging issue is related to the kernel configs based on the following observations:

1. The issue happens when booting (w/ hypervisor-fw) from a guest kernel compiled with Ubuntu 20.10 stock kernel source + __our custom kernel config__;
2. The issue does __not__ happen when booting (w/ hypervisor-fw) from a guest kernel compiled with Ubuntu 20.10 stock kernel source + __stock kernel config__;

@rbradford Do you think we will need to look further and understand the systemd crash better?

**Comment by likebreath** [comment] 2021-11-29 21:25
> How many namespaces are you using?

@tmakatos The systemd crash we saw was from the guest kernel booting, so I believe there are just default namespaces being used by the Linux kernel.

@jlevon Can you please elaborate more on the details you are looking for? The issue here can be easily reproducible by compiling a Linux kernel with [our custom kernel config](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/resources/linux-config-x86_64) and boot a guest from it with a NVMe  device. Also, this issue is not only for Cloud Hypervisor and can be reproduced with QEMU in the same way (details is https://github.com/cloud-hypervisor/cloud-hypervisor/issues/3352#issuecomment-972983104).

Please let me know if I miss anything or you have any questions. Thank you.

**Comment by tmakatos** [comment] 2021-11-30 09:32
> > How many namespaces are you using?
> @tmakatos The systemd crash we saw was from the guest kernel booting, so I believe there are just default namespaces being used by the Linux kernel.

The namespaces are provided by the NVMe controller, which is SPDK. How many NVMe namespaces do you tell SPDK to create? Can you paste the SPDK RPC commands you execute?

**Comment by sboeuf** [comment] 2021-11-30 09:48
@tmakatos 
>Can you paste the SPDK RPC commands you execute?

On that note, could you point or provide a well known configuration which works fine on your side? (I'm talking about the whole SPDK setup to expose an NVMe backend).

**Comment by jlevon** [comment] 2021-11-30 10:56
> @jlevon Can you please elaborate more on the details you are looking for

Perhaps I missed something but the only details here are "the systemd daemon sometimes core dump". Did I miss even a screenshot?

Presumably, taking the stock ubuntu kernel then disabling that MULTIPATH option is enough too, but I don't see that anybody tried that yet?

systemd / boot is often extremely picky in terms of configs/setup, so while it's possible this is a generic corruption issue that we don't see in any other scenario yet, there's a good chance it's just a guest-side issue.

> well known configuration which works fine on your side

Not that simple as we are diverged, but qemu client code of v0.93 and latest SPDK should be good enough as described in that other ticket.

**Comment by tmakatos** [comment] 2021-11-30 10:58
> > well known configuration which works fine on your side
> Not that simple as we are diverged, but qemu client code of v0.93 and latest SPDK should be good enough as described in that other ticket.

I'm working on providing such a configuration, won't be long.

**Comment by likebreath** [comment] 2021-11-30 14:15
> The namespaces are provided by the NVMe controller, which is SPDK. How many NVMe namespaces do you tell SPDK to create? Can you paste the SPDK RPC commands you execute?

@tmakatos Of course. Here you go (it is the same as what we have for our [vfio-user documentation](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/vfio-user.md#example-nvme-device)):

```
sudo ./build/bin/nvmf_tgt -i 0 -e 0xFFFF -m 0x1 &
sleep 2
sudo ./scripts/rpc.py nvmf_create_transport -t VFIOUSER

sudo ./scripts/rpc.py bdev_aio_create /tmp/test-vfio-user/test-disk.raw test 512

sudo ./scripts/rpc.py nvmf_create_subsystem nqn.2019-07.io.spdk:cnode -a -s test
sudo ./scripts/rpc.py nvmf_subsystem_add_ns nqn.2019-07.io.spdk:cnode test
sudo ./scripts/rpc.py nvmf_subsystem_add_listener nqn.2019-07.io.spdk:cnode -t VFIOUSER -a /tmp/test-vfio-user/nvme-vfio-user -s 0

```

**Comment by tmakatos** [comment] 2021-11-30 14:20
> `./scripts/rpc.py nvmf_subsystem_add_ns nqn.2019-07.io.spdk:cnode test`

You're only using one namespace, so `CONFIG_NVME_MULTIPATH` causing systemd to hang shouldn't happen.

Can you paste a screenshot of how systemd crashes/hangs when `CONFIG_NVME_MULTIPATH` is enabled? This is most likely either a systemd or a Linux kernel issue.

**Comment by jlevon** [comment] 2021-11-30 16:48
So, seems pretty likely that there's a systemd bug when handling certain service failures. Annoying to debug, because unfortunately systemd project didn't really consider this kind of emergency situation.

**Comment by tmakatos** [comment] 2021-12-01 10:23
Here's instructions on how to use SPDK: https://github.com/nutanix/libvfio-user/blob/tmakatos/issues/631/docs/spdk.md

**Closed** 2021-12-01 10:31 UTC
