### ISSUE TITLE
start vm failed for cloud hypervisor v36

### ISSUE THREAD

**Issue by grass-lu** [cloud-hypervisor/cloud-hypervisor#5917] opened 2023-11-06 08:35 UTC
**Describe the bug**

start vm failed for cloud hypervisor v36

[root@0m10poikkc1x2gj home]# ./cloud-hypervisor-static-aarch64-v36 --kernel ./hypervisor-fw --disk path=focal-server-cloudimg-arm64.raw,num_queues=4 --cpus boot=4,max=16 --memory size=1024M,hotplug_size=8192M --net tap=,mac=,ip=192.168.10.2,mask=255.255.255.0 --cmdline "console=ttyAMA0 root=/dev/vda1 rw" --api-socket /tmp/ch-socket --serial tty --console off
cloud-hypervisor: 157.210700ms: <vmm> WARN:arch/src/aarch64/fdt.rs:428 -- L2 cache shared with other cpus
cloud-hypervisor: 157.333620ms: <vmm> WARN:arch/src/aarch64/fdt.rs:428 -- L2 cache shared with other cpus
cloud-hypervisor: 157.432160ms: <vmm> WARN:arch/src/aarch64/fdt.rs:428 -- L2 cache shared with other cpus
cloud-hypervisor: 157.546340ms: <vmm> WARN:arch/src/aarch64/fdt.rs:428 -- L2 cache shared with other cpus

Booting with FDT
Found PCI device vendor=8086 device=d57 in slot=0
Found PCI device vendor=1af4 device=1042 in slot=1
Found PCI device vendor=1af4 device=1041 in slot=2
Found PCI device vendor=1af4 device=1044 in slot=3
PCI Device: 0:1.0 1af4:1042
Bar: type=MemorySpace32 address=0x2ff80000 size=0x80000
Bar: type=MemorySpace32 address=0x0 size=0x0
Bar: type=MemorySpace32 address=0x0 size=0x0
Bar: type=MemorySpace32 address=0x0 size=0x0
Bar: type=MemorySpace32 address=0x0 size=0x0
Bar: type=MemorySpace32 address=0x0 size=0x0
Updated BARs: type=MemorySpace32 address=2ff80000 size=80000
Updated BARs: type=MemorySpace32 address=0 size=0
Updated BARs: type=MemorySpace32 address=0 size=0
Updated BARs: type=MemorySpace32 address=0 size=0
Updated BARs: type=MemorySpace32 address=0 size=0
Updated BARs: type=MemorySpace32 address=0 size=0
Virtio block device configured. Capacity: 4612096 sectors
Found EFI partition
Filesystem ready
Error loading default entry: File(NotFound)
Using EFI boot.
Found bootloader: \EFI\BOOT\BOOTAA64.EFI
Executable loaded
error: no suitable video mode found.
cloud-hypervisor: 1.127963s: <_disk0_q0> ERROR:virtio-devices/src/thread_helper.rs:55 -- Error running worker: HandleEvent(Failed to process queue (complete): MissingEntryRequestList)

**To Reproduce**
Steps to reproduce the behaviour:
1、 start vm 
command line：
 ./cloud-hypervisor-static-aarch64-v36 --kernel ./hypervisor-fw --disk path=focal-server-cloudimg-arm64.raw,num_queues=4 --cpus boot=4,max=16 --memory size=1024M,hotplug_size=8192M --net tap=,mac=,ip=192.168.10.2,mask=255.255.255.0 --cmdline "console=ttyAMA0 root=/dev/vda1 rw" --api-socket /tmp/ch-socket --serial tty --console off

cloud hypervisor v35 is ok

**Version**

Output of `cloud-hypervisor --version`:

[root@0m10poikkc1x2gj home]# ./cloud-hypervisor-static-aarch64-v36 -V
cloud-hypervisor v36.0.0

Did you build from source, if so build command line (e.g. features):

**VM configuration**

What command line did you run (or JSON config data):

Guest OS version details:

Host OS version details:

**Logs**

Output of `cloud-hypervisor -v` from either standard error or via `--log-file`:

Linux kernel output:

**Comment by likebreath** [comment] 2023-11-06 20:42
Given the error you saw is from vitio-block, it is likely related to #5856. Can please try and see if works for you: `--disk path=focal-server-cloudimg-arm64.raw,num_queues=4,_disable_aio=true`? 

Can you also share your host OS details?

**Comment by grass-lu** [comment] 2023-11-07 01:16
it doesn't appear in my aarch64 machine. But it apper in my x86 machine.  
the command line:
 ./cloud-hypervisor-static --kernel ./hypervisor-fw --disk path=focal-server-cloudimg-amd64.raw,num_queues=4  --cpus boot=4,max=16 --memory size=1024M --net tap=,mac=,ip=192.168.10.2,mask=255.255.255.0 --cmdline "console=ttyS0 root=/dev/vda1 rw" --api-socket /tmp/ch-socket --serial tty --console off -vvv --log-file /tmp/start.log   
the start log is:
[start.log](https://github.com/cloud-hypervisor/cloud-hypervisor/files/13274335/start.log)

host os:
[root@ceasphere-node-1 cloud-hypervisor]# uname -ar
Linux ceasphere-node-1 4.18.0-193.el8.x86_64 #1 SMP Fri May 8 10:59:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

i try the command line ,it work good and vm started succesfully
./cloud-hypervisor-static --kernel ./hypervisor-fw --disk path=focal-server-cloudimg-amd64.raw,num_queues=4,_disable_aio=true --cpus boot=4,max=16 --memory size=1024M --net tap=,mac=,ip=192.168.10.2,mask=255.255.255.0 --cmdline console=ttyS0 root=/dev/vda1 rw --api-socket /tmp/ch-socket --serial tty --console off

**Comment by michael2012z** [comment] 2023-11-07 12:00
@grass-lu Just to confirm, was the failure that you have reported originally on the arm64 host resolved by appending the `_disable_aio=true` option?

**Comment by rbradford** [comment] 2023-11-07 13:34
This kernel is much older than the minimum supported kernel which is 5.13.

**Comment by likebreath** [comment] 2023-11-07 18:23
> host os: [root@ceasphere-node-1 cloud-hypervisor]# uname -ar Linux ceasphere-node-1 4.18.0-193.el8.x86_64 #1 SMP Fri May 8 10:59:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
> 
> i try the command line ,it work good and vm started succesfully ./cloud-hypervisor-static --kernel ./hypervisor-fw --disk path=focal-server-cloudimg-amd64.raw,num_queues=4,_disable_aio=true --cpus boot=4,max=16 --memory size=1024M --net tap=,mac=,ip=192.168.10.2,mask=255.255.255.0 --cmdline console=ttyS0 root=/dev/vda1 rw --api-socket /tmp/ch-socket --serial tty --console off

Then it is pretty clear that the `aio` probing believes `AIO` is supported while it does not. @thomasbarrett do you expect the AIO probing we have now works on such an old kernel?

With that being said, @grass-lu's host kernel is way too old and should be upgraded to v5.13 for using Cloud Hypervisor properly. 

Closing the issue now. Please reopen if you encounter the same issue on a newer kernel.

**Closed by likebreath** 2023-11-07 18:23 UTC

**Comment by grass-lu** [comment] 2023-11-08 00:55
@likebreath 
aio is enabled and supported
[root@ceasphere-node-1 ~]# cat /boot/config-4.18.0-193.el8.x86_64 | grep -i aio
CONFIG_AIO=y
CONFIG_DELL_WMI_AIO=m

**Comment by grass-lu** [comment] 2023-11-08 01:16
By the way， what is the command line for pci device hotplug in aarch64 ？

**Comment by likebreath** [comment] 2023-11-08 16:20
> @likebreath aio is enabled and supported [root@ceasphere-node-1 ~]# cat /boot/config-4.18.0-193.el8.x86_64 | grep -i aio CONFIG_AIO=y CONFIG_DELL_WMI_AIO=m

Okay. Then it could a issue from the aio backend. @thomasbarrett any thoughts?

For hotplug, please check this documentation: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/hotplug.md#pci-device-hot-plug. Note aarch64 requires to use uefi firmware.

**Comment by thomasbarrett** [comment] 2023-11-08 16:30
It is very possible that the aio backend is using some feature or behavior of aio that is not present in older kernels.
 
I will look into changes to aio between 4.18 and 5.13 to see if we can at least fall back successfully to synchronous reads.

**Comment by thomasbarrett** [comment] 2023-11-08 17:06
Based on the error message, I believe that [this is the cause](https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5930/files).

**Comment by thomasbarrett** [comment] 2023-11-10 03:34
@grass-lu, do you still see the same problem on the `main` branch of cloud-hypervisor?

**Comment by grass-lu** [comment] 2023-11-10 05:54
it's solved on the main branch
